"use client";

import { BriefcaseBusiness, ChevronDown, CircleHelp, Save } from "lucide-react";
import { useState } from "react";

import { createWorkstation, saveAnalysisMetadata } from "@/app/panel/analizy/[id]/metadata-actions";
import { calculateAnalysisCompleteness, type AnalysisMetadata, type AnalysisCategory, type Workstation } from "@/types/analysis-context";

export function AnalysisContextEditor({ analysisId, metadata, workstations, categories }: { analysisId: string; metadata: AnalysisMetadata; workstations: Workstation[]; categories: AnalysisCategory[] }) {
  const [editing, setEditing] = useState(false);
  const completeness = calculateAnalysisCompleteness(metadata);
  const selected = new Set(metadata.categories.map((item) => item.id));
  const groups = categories.reduce((result, item) => { const current = result.get(item.group_name) ?? []; current.push(item); result.set(item.group_name, current); return result; }, new Map<string, AnalysisCategory[]>());
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 text-slate-950 shadow-sm sm:p-7" aria-labelledby="analysis-context-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-emerald-700"><BriefcaseBusiness className="size-4" /> Informacje o analizie</p><h2 id="analysis-context-title" className="mt-2 text-xl font-bold">{metadata.workstation?.name ?? "Stanowisko nieprzypisane"}</h2><div className="mt-2 flex flex-wrap gap-2">{metadata.categories.map((item) => <span key={item.id} className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-700">{item.group_name}: {item.name}</span>)}</div></div><button type="button" onClick={() => setEditing((value) => !value)} aria-expanded={editing} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-emerald-600">{editing ? "Zamknij" : "Edytuj informacje"}</button></div>
    <div className="mt-5"><div className="flex justify-between text-xs font-medium"><span>Kompletność danych formularza</span><span>{completeness.percentage}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${completeness.percentage}%` }} /></div><p className="mt-2 flex items-center gap-2 text-xs text-slate-500"><CircleHelp className="size-4" /> To kompletność kontekstu, nie dokładność AI.</p></div>
    {!!completeness.missing.length && <details className="mt-5 rounded-2xl bg-amber-50 p-4"><summary className="flex cursor-pointer items-center justify-between text-sm font-semibold text-amber-950">Dane do uzupełnienia ({completeness.missing.length})<ChevronDown className="size-4" /></summary><ul className="mt-3 space-y-2 text-sm text-amber-900">{completeness.missing.map((item) => <li key={item.id}>• {item.label} <span className="text-xs opacity-70">— {item.neededFor.join(", ")}</span></li>)}</ul></details>}
    {editing && <form action={saveAnalysisMetadata} className="mt-6 grid gap-4 border-t border-slate-200 pt-6 sm:grid-cols-2"><input type="hidden" name="analysis_id" value={analysisId} /><Field name="title" label="Nazwa analizy" defaultValue={metadata.title} required /><Field name="analysis_date" label="Data analizy" type="date" defaultValue={metadata.analysis_date ?? ""} /><label className="text-sm font-medium">Stanowisko<select name="workstation_id" defaultValue={metadata.workstation?.id ?? ""} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">Nie przypisano</option>{workstations.map((item) => <option key={item.id} value={item.id}>{item.name}{item.code ? ` (${item.code})` : ""}</option>)}</select></label><Field name="process_name" label="Proces / czynność" defaultValue={metadata.context.process_name ?? ""} /><Field name="department" label="Dział" defaultValue={metadata.context.department ?? ""} /><Field name="area" label="Obszar / lokalizacja" defaultValue={metadata.context.area ?? ""} /><Field name="line_machine" label="Linia / maszyna" defaultValue={metadata.context.line_machine ?? ""} /><Field name="author_name" label="Autor analizy" defaultValue={metadata.context.author_name ?? ""} /><Textarea name="activity_description" label="Opis analizowanej czynności" defaultValue={metadata.context.activity_description ?? ""} /><Textarea name="notes" label="Notatki" defaultValue={metadata.context.notes ?? ""} /><Textarea name="description" label="Opis analizy" defaultValue={metadata.description ?? ""} /><fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Kategorie</legend>{[...groups].map(([group, items]) => <div key={group} className="mt-3"><p className="text-xs font-semibold uppercase text-slate-500">{group}</p><div className="mt-2 flex flex-wrap gap-2">{items.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="category_id" value={item.id} defaultChecked={selected.has(item.id)} />{item.name}</label>)}</div></div>)}</fieldset><button className="sm:col-span-2 inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 font-semibold text-white"><Save className="size-4" />Zapisz informacje</button></form>}
    {editing && <details className="mt-5 border-t border-slate-200 pt-5"><summary className="cursor-pointer text-sm font-semibold">+ Utwórz nowe stanowisko</summary><form action={createWorkstation} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="analysis_id" value={analysisId} /><Field name="name" label="Nazwa stanowiska" required /><Field name="code" label="Kod stanowiska" /><Field name="department" label="Dział" /><Field name="area" label="Obszar" /><button className="min-h-11 rounded-xl border border-emerald-700 font-semibold text-emerald-800 sm:col-span-2">Utwórz stanowisko</button></form></details>}
  </section>;
}

function Field({ name, label, defaultValue = "", type = "text", required = false }: { name: string; label: string; defaultValue?: string; type?: string; required?: boolean }) { return <label className="text-sm font-medium">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3" /></label>; }
function Textarea({ name, label, defaultValue }: { name: string; label: string; defaultValue: string }) { return <label className="text-sm font-medium">{label}<textarea name={name} defaultValue={defaultValue} rows={3} className="mt-1 w-full rounded-xl border border-slate-300 p-3" /></label>; }
