import type { Vector3Cm } from "../../types/photo-scene";
import { add3, distance3, lerp3, sub3, v3 } from "../photo-scene/vector3.ts";
import type { BodyRegion, ClearanceItem, ErgonomicsHumanInput, ErgonomicsObjectInput } from "./types.ts";

type Proxy={region:BodyRegion;a:Vector3Cm;b:Vector3Cm;radius:number};type Aabb={min:Vector3Cm;max:Vector3Cm};
export function analyzeClearance(human:ErgonomicsHumanInput,objects:ErgonomicsObjectInput[]):ClearanceItem[]{const proxies=humanProxies(human),result:ClearanceItem[]=[];for(const object of objects){const box=aabb(object);if(!box){for(const region of uniqueRegions(proxies))result.push({humanId:human.id,objectId:object.id,bodyRegion:region,level:"UNKNOWN_GEOMETRY",minimumClearanceCm:null,quality:0,source:"UNKNOWN"});continue}for(const proxy of proxies){const distance=distanceCapsuleAabb(proxy,box),clearance=distance-proxy.radius;result.push({humanId:human.id,objectId:object.id,bodyRegion:proxy.region,level:clearance<-.1?"PENETRATION":clearance<=.1?"CONTACT":"CLEAR",minimumClearanceCm:Math.round(clearance*1000)/1000,quality:object.geometry?.geometryQuality==="COMPLETE"?1:.5,source:object.provenance})}}return collapse(result)}
function humanProxies(h:ErgonomicsHumanInput):Proxy[]{const j=h.jointPositionsCm,d=h.profile.physicalDimensions,p=(region:BodyRegion,a:string,b:string,r:number):Proxy=>({region,a:j[a],b:j[b],radius:r});return[p("HEAD","neck","headTop",d.headHeightCm*.28),p("TORSO","pelvis","chest",Math.max(d.waistWidthCm,d.chestDepthCm)*.35),p("LEFT_ARM","leftShoulder","leftElbow",d.upperArmThicknessCm*.5),p("LEFT_ARM","leftElbow","leftWrist",d.forearmThicknessCm*.5),p("RIGHT_ARM","rightShoulder","rightElbow",d.upperArmThicknessCm*.5),p("RIGHT_ARM","rightElbow","rightWrist",d.forearmThicknessCm*.5),p("LEFT_HAND","leftWrist","leftHand",d.handWidthCm*.3),p("RIGHT_HAND","rightWrist","rightHand",d.handWidthCm*.3),p("LEFT_LEG","leftHip","leftKnee",d.thighThicknessCm*.5),p("LEFT_LEG","leftKnee","leftFoot",d.calfThicknessCm*.5),p("RIGHT_LEG","rightHip","rightKnee",d.thighThicknessCm*.5),p("RIGHT_LEG","rightKnee","rightFoot",d.calfThicknessCm*.5)]}
function aabb(object:ErgonomicsObjectInput):Aabb|null{const g=object.geometry;if(!g||g.geometryQuality!=="COMPLETE")return null;const d=g.dimensionsCm,x=d.width??d.diameter,y=d.height??d.length,z=d.depth??d.diameter;if(!x||!y||!z)return null;const half=v3(x/2,y/2,z/2);return{min:sub3(g.positionCm,half),max:add3(g.positionCm,half)}}
function distanceCapsuleAabb(proxy:Proxy,box:Aabb){let best=Infinity;for(let i=0;i<=20;i++){const p=lerp3(proxy.a,proxy.b,i/20),q=v3(clamp(p.x,box.min.x,box.max.x),clamp(p.y,box.min.y,box.max.y),clamp(p.z,box.min.z,box.max.z));best=Math.min(best,distance3(p,q))}return best}
function collapse(items:ClearanceItem[]){const map=new Map<string,ClearanceItem>();for(const item of items){const key=`${item.objectId}:${item.bodyRegion}`,old=map.get(key);if(!old||rank(item.level)>rank(old.level)||(item.minimumClearanceCm??Infinity)<(old.minimumClearanceCm??Infinity))map.set(key,item)}return[...map.values()]}
function rank(level:ClearanceItem["level"]){return{UNKNOWN_GEOMETRY:0,CLEAR:1,CONTACT:2,PENETRATION:3}[level]}
function uniqueRegions(items:Proxy[]){return[...new Set(items.map((item)=>item.region))]}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
