import type { ClearanceItem, GripAssessment, JointAngleSet, ReachAssessment, SceneFinding, SceneRecommendation, VisionResult, WorkHeightResult } from "./types.ts";

export function buildFindings(input:{humanId:string;angles:JointAngleSet;workHeight:WorkHeightResult|null;reach:ReachAssessment[];clearance:ClearanceItem[];vision:VisionResult[];grip:GripAssessment[];taskCollision:boolean}):SceneFinding[]{const out:SceneFinding[]=[];const add=(type:SceneFinding["type"],priority:SceneFinding["priority"],region:SceneFinding["bodyRegion"],objectId:string|null,measurement:string,value:number|null,rule:string,quality:number,description:string)=>out.push({id:`${input.humanId}:${type}:${objectId??"human"}:${out.length}`,type,priority,humanId:input.humanId,bodyRegion:region,objectId,taskStepId:null,measurement,value,rule,quality,source:"DERIVED",description});
  const angle=(name:string)=>input.angles[name]?.value??null,trunk=angle("trunk_flexion_deg"),twist=angle("trunk_twist_deg"),neck=angle("neck_flexion_deg");if(trunk!==null&&Math.abs(trunk)>20)add("TRUNK_FLEXION",Math.abs(trunk)>45?"HIGH":"MEDIUM","TORSO",null,"trunk_flexion_deg",trunk,"technical_geometry_band_abs_gt_20",.95,"Tułów jest wyraźnie zgięty względem miednicy.");if(twist!==null&&Math.abs(twist)>15)add("TRUNK_ROTATION","MEDIUM","TORSO",null,"trunk_twist_deg",twist,"technical_geometry_band_abs_gt_15",.95,"Tułów jest obrócony względem miednicy.");if(neck!==null&&Math.abs(neck)>20)add("NECK_FLEXION","MEDIUM","NECK",null,"neck_flexion_deg",neck,"technical_geometry_band_abs_gt_20",.95,"Szyja jest wyraźnie zgięta.");
  for(const side of ["left","right"] as const){const shoulder=angle(`${side}_shoulder_elevation_deg`),wrist=angle(`${side}_wrist_deviation_deg`);if(shoulder!==null&&shoulder>60)add("SHOULDER_ELEVATION",shoulder>90?"HIGH":"MEDIUM",side==="left"?"LEFT_ARM":"RIGHT_ARM",null,`${side}_shoulder_elevation_deg`,shoulder,"technical_geometry_band_gt_60",.95,`Ramię ${side==="left"?"lewe":"prawe"} jest uniesione.`);if(wrist!==null&&Math.abs(wrist)>15)add("WRIST_DEVIATION","MEDIUM",side==="left"?"LEFT_HAND":"RIGHT_HAND",null,`${side}_wrist_deviation_deg`,wrist,"technical_geometry_band_abs_gt_15",.9,"Nadgarstek jest odchylony od pozycji neutralnej.")}
  if(input.workHeight&&input.workHeight.classification!=="UNKNOWN"&&Math.abs(input.workHeight.differenceFromElbowCm.value??0)>5)add((input.workHeight.differenceFromElbowCm.value??0)>0?"HIGH_WORK_SURFACE":"LOW_WORK_SURFACE","MEDIUM","TORSO",input.workHeight.objectId,"surface_vs_elbow_cm",input.workHeight.differenceFromElbowCm.value,"task_dependent_reference_difference_gt_5",input.workHeight.surfaceHeightCm.quality,"Wysokość powierzchni różni się od wysokości łokcia operatora.");
  for(const reach of input.reach){if(reach.zone==="OUTSIDE_ZONE")add("UNREACHABLE_TARGET","HIGH",reach.hand==="LEFT"?"LEFT_ARM":"RIGHT_ARM",reach.objectId,"reach_margin_cm",reach.reachMarginCm,"outside_sampled_reach_envelope",reach.quality,"Punkt znajduje się poza geometrycznym zasięgiem.");else if(reach.zone==="MAXIMUM_ZONE")add("REACH_AT_LIMIT","MEDIUM",reach.hand==="LEFT"?"LEFT_ARM":"RIGHT_ARM",reach.objectId,"reach_margin_cm",reach.reachMarginCm,"maximum_zone",reach.quality,"Punkt znajduje się w maksymalnej strefie dosiężności.");if(reach.crossBody)add("CROSS_BODY_REACH","INFORMATIONAL",reach.hand==="LEFT"?"LEFT_ARM":"RIGHT_ARM",reach.objectId,"cross_body",1,"target_across_body_midline",reach.quality,"Ręka sięga na przeciwną stronę osi ciała.");if((reach.targetHeightRelativeToShoulderCm??-1)>0)add("OVERHEAD_REACH","MEDIUM",reach.hand==="LEFT"?"LEFT_ARM":"RIGHT_ARM",reach.objectId,"above_shoulder_cm",reach.targetHeightRelativeToShoulderCm,"target_above_shoulder",reach.quality,"Cel znajduje się powyżej barku.");if((reach.targetHeightRelativeToKneeCm??1)<0)add("LOW_REACH","MEDIUM",reach.hand==="LEFT"?"LEFT_ARM":"RIGHT_ARM",reach.objectId,"below_knee_cm",reach.targetHeightRelativeToKneeCm,"target_below_knee",reach.quality,"Cel znajduje się poniżej kolana.")}
  for(const clearance of input.clearance)if(clearance.level==="PENETRATION"||clearance.level==="CONTACT")add(clearance.level==="PENETRATION"?"COLLISION":"INSUFFICIENT_CLEARANCE",clearance.level==="PENETRATION"?"HIGH":"MEDIUM",clearance.bodyRegion,clearance.objectId,"minimum_clearance_cm",clearance.minimumClearanceCm,clearance.level.toLowerCase(),clearance.quality,clearance.level==="PENETRATION"?"Bryła ciała przecina geometrię obiektu.":"Bryła ciała styka się z obiektem.");
  for(const grip of input.grip)if(grip.geometryStatus==="GEOMETRY_INVALID"||grip.geometryStatus==="GEOMETRY_PARTIAL")add("GRIP_GEOMETRY_ISSUE",grip.geometryStatus==="GEOMETRY_INVALID"?"HIGH":"MEDIUM",grip.hand==="LEFT"?"LEFT_HAND":"RIGHT_HAND",grip.objectId,"grip_geometry",null,grip.geometryStatus,.85,"Geometria przedmiotu nie odpowiada w pełni wymiarom dłoni.");
  for(const view of input.vision)if(view.verticalAngleDeg!==null&&Math.abs(view.verticalAngleDeg)>30)add("VISUAL_TARGET_ANGLE","INFORMATIONAL","HEAD",view.objectId,"vertical_view_angle_deg",view.verticalAngleDeg,"technical_view_angle_abs_gt_30",view.quality,"Cel wzrokowy wymaga wyraźnego skierowania wzroku w pionie.");if(input.taskCollision)add("TASK_PATH_COLLISION","HIGH",null,null,"task_collision",1,"motion_path_collision",1,"Próbkowana ścieżka zadania zawiera konflikt geometryczny.");return out.sort((a,b)=>priority(b.priority)-priority(a.priority)||b.quality-a.quality).slice(0,7)}
export function buildRecommendations(findings:SceneFinding[]):SceneRecommendation[]{return findings.slice(0,5).filter((f)=>f.quality>=.5).map((finding)=>({id:`recommendation:${finding.id}`,sourceFindingId:finding.id,priority:finding.priority,text:recommendationText(finding.type),reason:finding.description,quality:finding.quality}))}
function recommendationText(type:SceneFinding["type"]){if(type==="UNREACHABLE_TARGET"||type==="REACH_AT_LIMIT")return"Rozważ przesunięcie punktu roboczego bliżej operatora i ponownie przelicz wariant.";if(type==="HIGH_WORK_SURFACE"||type==="LOW_WORK_SURFACE")return"Rozważ zmianę wysokości powierzchni w jawnie określonym zakresie i porównaj warianty.";if(type==="COLLISION"||type==="INSUFFICIENT_CLEARANCE"||type==="TASK_PATH_COLLISION")return"Rozważ zwiększenie wolnej przestrzeni lub zmianę przebiegu ruchu.";if(type==="OVERHEAD_REACH")return"Rozważ obniżenie lub przybliżenie punktu obsługi.";if(type==="LOW_REACH")return"Rozważ podniesienie punktu pobrania lub ograniczenie konieczności sięgania nisko.";return"Sprawdź zmianę geometrii stanowiska dotyczącą wskazanego odchylenia."}
function priority(value:SceneFinding["priority"]){return{HIGH:3,MEDIUM:2,INFORMATIONAL:1}[value]}
