import type { CollisionResult3D } from "../../types/photo-scene";
import { assessSceneReba, assessSceneRula } from "./assessment-adapter.ts";
import { analyzeClearance } from "./clearance.ts";
import { buildFindings, buildRecommendations } from "./findings.ts";
import { createPostureSnapshot } from "./joint-angles.ts";
import { assessTaskSequence } from "./task.ts";
import type { MissingDatum, QualityLevel, SceneAssessmentResult, SceneErgonomicsInput } from "./types.ts";
import { SCENE_ASSESSMENT_SCHEMA, SCENE_ERGONOMICS_VERSION, SCENE_REPORT_VERSION } from "./types.ts";
import { analyzeGrip, analyzeVision } from "./vision-grip.ts";
import { analyzeReachPoints, analyzeWorkHeight } from "./workspace.ts";

export function assessScene(input:SceneErgonomicsInput):SceneAssessmentResult{
  validateInput(input);const humans:SceneAssessmentResult["humans"]={},allFindings=[] as SceneAssessmentResult["findings"],missing=buildMissingData(input);let taskResult:SceneAssessmentResult["task"]=null;
  for(const human of input.humans){const clearance=analyzeClearance(human,input.objects),collisions=clearanceToCollisions(clearance),posture=createPostureSnapshot(human,collisions),workHeight=analyzeWorkHeight(human,input.objects,input.manualContext),reach=analyzeReachPoints(human,input.objects),vision=analyzeVision(human,input.objects),grip=analyzeGrip(human,input.objects),rula={left:assessSceneRula(posture.jointAngles,"LEFT",input.manualContext),right:assessSceneRula(posture.jointAngles,"RIGHT",input.manualContext)},reba={left:assessSceneReba(posture.jointAngles,"LEFT",input.manualContext),right:assessSceneReba(posture.jointAngles,"RIGHT",input.manualContext)};const task=input.task?.steps.some((step)=>step.humanId===human.id)?assessTaskSequence(input.task,human,input.objects):null;if(task)taskResult=task;const findings=buildFindings({humanId:human.id,angles:posture.jointAngles,workHeight,reach,clearance,vision,grip,taskCollision:Boolean(task?.firstCollision)});allFindings.push(...findings);humans[human.id]={posture,workHeight,reach,clearance,vision,grip,rula,reba}}
  const findings=allFindings.sort((a,b)=>rank(b.priority)-rank(a.priority)||b.quality-a.quality).slice(0,7),recommendations=buildRecommendations(findings),quality=calculateQuality(input,humans,missing);
  return{schemaVersion:SCENE_ASSESSMENT_SCHEMA,engineVersion:SCENE_ERGONOMICS_VERSION,reportVersion:SCENE_REPORT_VERSION,calculatedAt:input.createdAt,sceneId:input.sceneId,sceneRevision:input.sceneRevision,sceneSchemaVersion:"1.4",status:"CURRENT",humans,task:taskResult,findings,recommendations,missingData:missing,quality,limitations:["analysis_uses_user_defined_3d_scene","single_photo_depth_may_be_incomplete","geometry_findings_are_not_safety_decisions","rula_reba_are_screening_methods","specialist_review_required"],traceability:{sceneRevision:input.sceneRevision,humanIds:input.humans.map((h)=>h.id),taskId:input.task?.id??null,engineVersion:SCENE_ERGONOMICS_VERSION,calculatedAt:input.createdAt}};
}
export function assessmentStatus(result:SceneAssessmentResult,currentRevision:string){return result.sceneRevision===currentRevision?"CURRENT" as const:"STALE" as const}
function validateInput(input:SceneErgonomicsInput){if(input.schemaVersion!=="scene-ergonomics-input-v1")throw new Error("unsupported_scene_ergonomics_input");if(!input.sceneId||!input.sceneRevision)throw new Error("missing_scene_traceability");if(!input.humans.length)throw new Error("scene_has_no_visible_human")}
function buildMissingData(input:SceneErgonomicsInput):MissingDatum[]{const list:MissingDatum[]=[];const add=(id:string,label:string,reason:string,materialFor:string[],priority:MissingDatum["priority"])=>list.push({id,label,reason,materialFor,priority});for(const object of input.objects)if(!object.geometry||object.geometry.geometryQuality!=="COMPLETE")add(`depth:${object.id}`,`Uzupełnij geometrię 3D: ${object.name}`,"Bez kompletnej głębokości clearance i line-of-sight mogą pozostać nieznane.",["clearance","vision"],"RECOMMENDED");if(input.manualContext.objectMassKg===null)add("object-mass","Masa przenoszonego przedmiotu","Masa nie jest estymowana ze zdjęcia.",["external_load","REBA"],"RECOMMENDED");if(input.manualContext.rulaForceLoad===null)add("rula-force","Siła lub obciążenie RULA","Brak wartości pozostawia wynik RULA jako zakres.",["RULA"],"REQUIRED");if(input.manualContext.rulaMuscleUse===null)add("rula-muscle","Długotrwałe lub powtarzalne użycie mięśni","Brak wartości pozostawia wynik RULA jako zakres.",["RULA"],"RECOMMENDED");add("rula-midline","Relacja przedramienia do osi ciała","Aktualny rig nie zapisuje jeszcze jawnego komponentu RULA dla pracy w poprzek osi.",["RULA"],"RECOMMENDED");add("body-support","Podparcie i rozkład ciężaru","Statyczna geometria nóg nie potwierdza równowagi ani jakości podparcia.",["RULA","REBA"],"RECOMMENDED");if(input.manualContext.rebaLoadForce===null)add("reba-load","Obciążenie lub siła REBA","Brak wartości pozostawia wynik REBA jako zakres.",["REBA"],"REQUIRED");if(input.manualContext.rebaCoupling===null)add("reba-coupling","Jakość chwytu REBA","Geometryczny typ chwytu nie zastępuje kategorii coupling.",["REBA"],"REQUIRED");if(input.manualContext.rebaActivity===null)add("reba-activity","Aktywność REBA","Statyczna scena nie określa aktywności i powtarzalności.",["REBA"],"RECOMMENDED");if(input.manualContext.postureDurationSeconds===null)add("duration","Czas utrzymywania pozycji","Ekspozycja pozostaje nieznana.",["exposure"],"OPTIONAL");if(input.manualContext.repetitionsPerMinute===null)add("repetition","Liczba powtórzeń na minutę","Powtarzalność nie jest zgadywana ze statycznej sceny.",["exposure"],"OPTIONAL");return list}
function calculateQuality(input:SceneErgonomicsInput,humans:SceneAssessmentResult["humans"],missing:MissingDatum[]){const completeObjects=input.objects.length?input.objects.filter((o)=>o.geometry?.geometryQuality==="COMPLETE").length/input.objects.length:0,posture=input.humans.length?1:0,reach=input.objects.some((o)=>o.interactionPoints.length)?1:.5,manual=1-missing.filter((m)=>m.priority==="REQUIRED").length/Math.max(1,missing.length),coverage=Math.max(0,Math.min(1,(completeObjects+posture+reach+manual)/4)),level=(value:number):QualityLevel=>value>=.85?"HIGH":value>=.55?"PARTIAL":value>0?"LOW":"UNKNOWN";const methods=Object.values(humans),modules:Record<string,QualityLevel>={posture:level(posture),reach:level(reach),collision:level(completeObjects),RULA:methods.every((h)=>h.rula.left.status==="COMPLETE"&&h.rula.right.status==="COMPLETE")?"HIGH":"PARTIAL",REBA:methods.every((h)=>h.reba.left.status==="COMPLETE"&&h.reba.right.status==="COMPLETE")?"HIGH":"PARTIAL"};return{overall:level(coverage),modules,coverage:Math.round(coverage*1e6)/1e6}}
function clearanceToCollisions(items:ReturnType<typeof analyzeClearance>):CollisionResult3D[]{return items.filter((i)=>i.level==="CONTACT"||i.level==="PENETRATION").map((i)=>({level:i.level,humanPart:i.bodyRegion,objectId:i.objectId,contactPointCm:null,penetrationDepthCm:i.minimumClearanceCm===null?null:Math.max(0,-i.minimumClearanceCm),geometryQuality:i.quality===1?"COMPLETE":"PARTIAL"}))}
function rank(value:"HIGH"|"MEDIUM"|"INFORMATIONAL"){return{HIGH:3,MEDIUM:2,INFORMATIONAL:1}[value]}
