import type { CollisionResult3D, Vector3Cm } from "../../types/photo-scene";
import { solveTwoBoneIk3d } from "../photo-scene/ik-3d.ts";
import { lerp3 } from "../photo-scene/vector3.ts";
import { analyzeClearance } from "./clearance.ts";
import { calculateJointAngles3d } from "./joint-angles.ts";
import { analyzeReachPoint } from "./workspace.ts";
import type { ErgonomicsHumanInput, ErgonomicsObjectInput, SceneTaskSequence, TaskAssessment, TaskSample } from "./types.ts";

export function assessTaskSequence(task:SceneTaskSequence,human:ErgonomicsHumanInput,objects:ErgonomicsObjectInput[]):TaskAssessment{
  const samples:TaskSample[]=[];for(const step of task.steps){if(step.humanId!==human.id)continue;const object=objects.find((o)=>o.id===step.targetObjectId),point=object?.interactionPoints.find((p)=>p.id===step.targetPointId);if(!object||!point)continue;const side=step.hand==="LEFT"?"left":"right",start=human.jointPositionsCm[`${side}Wrist`],count=24;for(let i=0;i<count;i++){const progress=i/(count-1),target=lerp3(start,point.positionCm,progress),moved=moveArm(human,step.hand,target),reach=analyzeReachPoint(moved,object,{...point,positionCm:target},step.hand),clearance=analyzeClearance(moved,objects),collisions=clearance.filter((c)=>c.level==="CONTACT"||c.level==="PENETRATION").map((c):CollisionResult3D=>({level:c.level,humanPart:c.bodyRegion,objectId:c.objectId,contactPointCm:null,penetrationDepthCm:c.minimumClearanceCm===null?null:Math.max(0,-c.minimumClearanceCm),geometryQuality:c.quality===1?"COMPLETE":"PARTIAL"})),angles=calculateJointAngles3d(moved),rankingScore=rankSample(angles,reach.zone,collisions);samples.push({stepId:step.id,progress,angles,reach,collisions,rankingScore})}}
  const sorted=[...samples].sort((a,b)=>b.rankingScore-a.rankingScore),firstCollision=samples.find((s)=>s.collisions.length>0)??null,maximumReach=[...samples].sort((a,b)=>(a.reach?.reachMarginCm??Infinity)-(b.reach?.reachMarginCm??Infinity))[0]??null;
  const durations=task.steps.every((s)=>s.durationSeconds!==null),total=durations?task.steps.reduce((sum,s)=>sum+(s.durationSeconds??0)*(s.repetitions??1),0):null;
  return{taskId:task.id,samples,worstSample:sorted[0]??null,firstCollision,maximumReachSample:maximumReach,exposure:{known:durations,totalDurationSeconds:total,timeAtReachLimitSeconds:durations?exposure(samples,task,(s)=>s.reach?.zone==="MAXIMUM_ZONE"):null,elevatedArmSeconds:durations?exposure(samples,task,(s)=>Math.max(s.angles.left_shoulder_elevation_deg?.value??0,s.angles.right_shoulder_elevation_deg?.value??0)>60):null,trunkFlexionSeconds:durations?exposure(samples,task,(s)=>Math.abs(s.angles.trunk_flexion_deg?.value??0)>20):null}};
}
function moveArm(human:ErgonomicsHumanInput,hand:"LEFT"|"RIGHT",target:Vector3Cm):ErgonomicsHumanInput{const side=hand==="LEFT"?"left":"right",d=human.profile.physicalDimensions,joints=structuredClone(human.jointPositionsCm),result=solveTwoBoneIk3d(joints[`${side}Shoulder`],target,human.jointPositionsCm[`${side}Elbow`],d.upperArmLengthCm,d.forearmLengthCm);joints[`${side}Elbow`]=result.joint;joints[`${side}Wrist`]=result.end;joints[`${side}Hand`]=result.end;return{...human,jointPositionsCm:joints}}
function rankSample(angles:ReturnType<typeof calculateJointAngles3d>,zone:string,collisions:CollisionResult3D[]){let score=collisions.some((c)=>c.level==="PENETRATION")?100:collisions.length?50:0;score+=zone==="OUTSIDE_ZONE"?40:zone==="MAXIMUM_ZONE"?20:0;for(const name of ["trunk_flexion_deg","neck_flexion_deg","left_shoulder_elevation_deg","right_shoulder_elevation_deg","left_wrist_deviation_deg","right_wrist_deviation_deg"])score+=Math.min(20,Math.abs(angles[name]?.value??0)/5);return score}
function exposure(samples:TaskSample[],task:SceneTaskSequence,predicate:(sample:TaskSample)=>boolean){let total=0;for(const step of task.steps){const stepSamples=samples.filter((s)=>s.stepId===step.id);if(!stepSamples.length||step.durationSeconds===null)continue;total+=stepSamples.filter(predicate).length/stepSamples.length*step.durationSeconds*(step.repetitions??1)}return Math.round(total*1000)/1000}
