import type { Vector3Cm } from "../../types/photo-scene";
import { gripGeometryForDiameter } from "../photo-scene/hand-rig.ts";
import { directionAngles } from "./math3d.ts";
import type { ErgonomicsHumanInput, ErgonomicsObjectInput, GripAssessment, VisionResult } from "./types.ts";
import { add3, scale3, sub3, v3 } from "../photo-scene/vector3.ts";

export function analyzeVision(human:ErgonomicsHumanInput,objects:ErgonomicsObjectInput[]):VisionResult[]{const eye=eyePosition(human),results:VisionResult[]=[];for(const object of objects){const targets=object.interactionPoints.filter((point)=>["BUTTON","WORKING"].includes(point.type));if(!targets.length&&object.type==="MONITOR"&&object.geometry)targets.push({id:"screen-center",name:"Środek ekranu",type:"WORKING",positionCm:{...object.geometry.positionCm},hand:null});for(const target of targets){const angles=directionAngles(eye,target.positionCm),occlusion=lineOfSight(eye,target.positionCm,objects,object.id);results.push({humanId:human.id,objectId:object.id,pointId:target.id,distanceCm:round(angles.distance),verticalAngleDeg:round(angles.vertical),horizontalAngleDeg:round(angles.horizontal),blocked:occlusion.blocked,quality:occlusion.quality,reason:occlusion.reason})}}return results;}
export function analyzeGrip(human:ErgonomicsHumanInput,objects:ErgonomicsObjectInput[]):GripAssessment[]{const output:GripAssessment[]=[];for(const side of ["left","right"] as const){const hand=side==="left"?"LEFT":"RIGHT",objectId=human.heldObjectIds.find((id)=>objects.some((object)=>object.id===id))??null,object=objects.find((item)=>item.id===objectId),preset=human.hands[side].preset,wrist=human.jointRotationsDeg[`${side}Wrist`];if(!object?.geometry){output.push({humanId:human.id,hand,objectId,preset,geometryStatus:"UNKNOWN",massKg:null,massSource:"UNKNOWN",wristFlexionDeg:wrist?.x??null,wristDeviationDeg:wrist?.z??null,reasons:["no_held_object_or_geometry"]});continue}const d=object.geometry.dimensionsCm,diameter=d.diameter??Math.min(d.width??Infinity,d.depth??Infinity),result=Number.isFinite(diameter)?gripGeometryForDiameter(human.profile,diameter,preset):null;output.push({humanId:human.id,hand,objectId,preset,geometryStatus:result?.status==="GRIP_GEOMETRY_VALID"?"GEOMETRY_VALID":result?.status==="GRIP_GEOMETRY_PARTIAL"?"GEOMETRY_PARTIAL":result?.status==="GRIP_GEOMETRY_INVALID"?"GEOMETRY_INVALID":"UNKNOWN",massKg:object.geometry.massKg,massSource:object.geometry.massSource?"USER_PROVIDED":"UNKNOWN",wristFlexionDeg:wrist?.x??null,wristDeviationDeg:wrist?.z??null,reasons:result?.reason?[result.reason]:[]})}return output;}
function eyePosition(human:ErgonomicsHumanInput){const head=human.jointPositionsCm.head,top=human.jointPositionsCm.headTop;return add3(head,scale3(sub3(top,head),.42))}
function lineOfSight(start:Vector3Cm,end:Vector3Cm,objects:ErgonomicsObjectInput[],ignoredId:string){let unknown=false;for(const object of objects){if(object.id===ignoredId)continue;const box=objectBox(object);if(!box){if(object.geometry)unknown=true;continue}if(segmentAabb(start,end,box.min,box.max))return{blocked:true,quality:1,reason:"solid_geometry_blocks_line_of_sight"}}return unknown?{blocked:null,quality:.4,reason:"unknown_depth_on_possible_occluder"}:{blocked:false,quality:1,reason:null}}
function objectBox(object:ErgonomicsObjectInput){const g=object.geometry,d=g?.dimensionsCm;if(!g||g.geometryQuality!=="COMPLETE")return null;const x=d?.width??d?.diameter,y=d?.height??d?.length,z=d?.depth??d?.diameter;if(!x||!y||!z)return null;const half=v3(x/2,y/2,z/2);return{min:sub3(g.positionCm,half),max:add3(g.positionCm,half)}}
function segmentAabb(start:Vector3Cm,end:Vector3Cm,min:Vector3Cm,max:Vector3Cm){const d=sub3(end,start);let t0=0,t1=1;for(const axis of ["x","y","z"] as const){if(Math.abs(d[axis])<1e-9){if(start[axis]<min[axis]||start[axis]>max[axis])return false;continue}let a=(min[axis]-start[axis])/d[axis],b=(max[axis]-start[axis])/d[axis];if(a>b)[a,b]=[b,a];t0=Math.max(t0,a);t1=Math.min(t1,b);if(t0>t1)return false}return true}
function round(value:number){return Number.isFinite(value)?Math.round(value*1000)/1000:null}
