import { Search, UserRound, UsersRound } from "lucide-react";

import { requireAdmin } from "@/lib/auth/access";

export const dynamic = "force-dynamic";
export default async function UsersPage({ searchParams }: { searchParams: Promise<{ q?: string; company?: string; role?: string; status?: string }> }) {
  const raw = await searchParams; const q = clean(raw.q); const { supabase } = await requireAdmin();
  const { data: companies } = await supabase.from("companies").select("id,name").order("name");
  let query = supabase.from("profiles").select("id,full_name,email,role,company_id,company_role,job_title,account_status,created_at,last_seen_at,company:companies(id,name),position:company_positions(name)").order("created_at", { ascending: false });
  if (q) query = query.or(`full_name.ilike.%${q}%,email.ilike.%${q}%`); if (uuid(raw.company)) query = query.eq("company_id", raw.company!); if (["admin","member","reviewer"].includes(raw.role ?? "")) query = query.eq("company_role", raw.role!); if (["active","inactive","pending"].includes(raw.status ?? "")) query = query.eq("account_status", raw.status!);
  const { data, error } = await query;
  return <div className="dashboard-page"><header><p className="dashboard-eyebrow">Dostęp</p><h1 className="dashboard-title mt-2">Użytkownicy</h1><p className="dashboard-muted mt-2">Sprawdź przynależność do firmy, rolę, stanowisko i aktywność konta.</p></header>
    <form className="dashboard-card grid gap-3 p-4 md:grid-cols-[2fr_1fr_1fr_1fr_auto]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><input name="q" defaultValue={q} placeholder="Szukaj po imieniu i nazwisku" className="ui-input pl-10" /></label><Filter name="company" value={raw.company} options={[['','Wszystkie firmy'], ...(companies ?? []).map((item) => [item.id,item.name] as const)]} /><Filter name="role" value={raw.role} options={[["","Wszystkie role"],["admin","Admin firmy"],["reviewer","Reviewer"],["member","Użytkownik"]]} /><Filter name="status" value={raw.status} options={[["","Wszystkie statusy"],["active","Aktywny"],["inactive","Nieaktywny"],["pending","Oczekujący"]]} /><button className="ui-button-primary">Filtruj</button></form>
    {error ? <p className="dashboard-card border-red-200 p-6 text-red-700">Nie udało się pobrać użytkowników.</p> : <div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>Użytkownik</th><th>Firma</th><th>Rola</th><th>Stanowisko</th><th>Status</th><th>Aktywność</th></tr></thead><tbody>{data?.map((item) => <tr key={item.id}><td><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-violet-500/10 font-bold text-violet-600"><UserRound className="size-4" /></span><div className="min-w-0"><p className="font-bold">{item.full_name || "Bez nazwy"}</p><p className="max-w-56 truncate text-xs text-muted-foreground">{item.email || (item.role === "admin" ? "Super administrator" : "Brak adresu e-mail")}</p></div></div></td><td>{relationName(item.company) || "Bez firmy"}</td><td>{roleLabel(item.role, item.company_role)}</td><td>{relationName(item.position) || item.job_title || "—"}</td><td><Status value={item.account_status ?? "active"} /></td><td className="text-xs text-muted-foreground">{item.last_seen_at ? formatDate(item.last_seen_at) : `Dodano ${formatDate(item.created_at)}`}</td></tr>)}</tbody></table>{!data?.length && <div className="p-12 text-center"><UsersRound className="mx-auto size-9 text-muted-foreground" /><p className="mt-3 font-bold">Brak wyników</p></div>}</div>}
    <p className="text-xs text-muted-foreground">Edycja roli, stanowiska i statusu jest dostępna w profilu wybranej firmy.</p>
  </div>;
}
function Filter({ name, value, options }: { name: string; value?: string; options: ReadonlyArray<readonly [string,string]> }) { return <select name={name} defaultValue={value ?? ""} className="ui-input">{options.map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select>; }
function Status({ value }: { value: string }) { const map: Record<string,string> = { active: "Aktywny", inactive: "Nieaktywny", pending: "Oczekujący" }; return <span className={`dashboard-status ${value === "active" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : value === "pending" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-border bg-surface-muted text-muted-foreground"}`}>{map[value] ?? value}</span>; }
function relationName(value: unknown) { return Array.isArray(value) ? (value[0] as {name?:string}|undefined)?.name : (value as {name?:string}|null)?.name; }
function roleLabel(appRole: string, role: string | null) { if (appRole === "admin") return "Super admin"; return role === "admin" ? "Admin firmy" : role === "reviewer" ? "Reviewer" : "Użytkownik"; }
function clean(value?: string) { return (value ?? "").trim().slice(0,100).replace(/[,%()]/g," "); }
function uuid(value?: string): value is string { return Boolean(value && /^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(value)); }
function formatDate(value: string) { return new Intl.DateTimeFormat("pl-PL", { dateStyle: "medium" }).format(new Date(value)); }
