"use client";

import { AlertCircle, Calculator, CheckCircle2, ChevronDown, Factory, FlaskConical, Gauge, Scale, Weight } from "lucide-react";
import { useFormStatus } from "react-dom";

import { saveCompanyMethodInputs } from "@/app/panel/analizy/[id]/company-method-actions";
import { companyMethodSpecs, hazardSuggestions } from "@/lib/company-methods/specs";
import type { CompanyMethodsView } from "@/lib/company-methods/normalize";

export function CompanyMethodsSection({ analysisId, value, onSeek }: { analysisId: string; value: CompanyMethodsView | null; onSeek: (time: number) => void }) {
  const owas = value?.owas ?? null;
  const ejms = value?.ejms ?? null;
  const missing = value?.missingInputs ?? [];
  const dominantFrame = findDominantOwasFrame(owas);
  return <section className="review-panel" aria-labelledby="company-methods-title">
    <p className="review-eyebrow"><Factory className="size-4" /> Metody zakładowe</p>
    <div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 id="company-methods-title" className="text-2xl font-semibold">OWAS, EJMS i ocena kontekstowa</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Metody pozostają oddzielne od Risk Engine, RULA i REBA. Wartości masy, siły oraz odległości wymagają pomiaru lub potwierdzenia użytkownika.</p></div><span className="rounded-full border border-cyan-300/20 bg-cyan-300/[0.07] px-3 py-1.5 text-xs font-semibold text-cyan-100">{value?.version ?? "company-methods-v1.0-beta.1"}</span></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <MethodCard title="OWAS" icon={Weight} status={status(owas)} value={owasSummary(owas)} />
      <MethodCard title="EJMS" icon={Gauge} status={status(ejms)} value={ejmsSummary(ejms)} />
      <MethodCard title="Risk Score" icon={Calculator} status={status(value?.riskScore)} value={riskSummary(value?.riskScore)} />
      <MethodCard title="Czynniki mierzalne" icon={Scale} status={value?.measurableFactors.length ? "MANUAL" : "REQUIRES_DATA"} value={value?.measurableFactors.length ? "Pomiar zapisany" : "Wymaga P i Pmax"} />
      <MethodCard title="Chemia" icon={FlaskConical} status={status(value?.chemical)} value="Scoring automatyczny wyłączony" />
    </div>
    <CompanyMethodDetails owas={owas} ejms={ejms} />
    {dominantFrame && <button type="button" onClick={() => onSeek(dominantFrame.time)} className="mt-4 rounded-xl border border-cyan-300/20 bg-cyan-300/[0.06] px-4 py-3 text-left text-sm text-cyan-100 transition hover:bg-cyan-300/[0.1] focus-visible:outline-2 focus-visible:outline-cyan-200">Dominująca rozpoznana pozycja OWAS: kod {dominantFrame.code}, kategoria {dominantFrame.category}. Przejdź do {dominantFrame.time.toFixed(1)} s.</button>}
    <details className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[0.035] open:bg-amber-300/[0.05]">
      <summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 focus-visible:outline-2 focus-visible:outline-amber-200"><span><span className="flex items-center gap-2 font-semibold"><AlertCircle className="size-4 text-amber-300" />Dane wymagające uzupełnienia</span><span className="mt-1 block text-sm text-slate-400">{missing.length ? `${missing.length} pól może zmienić wynik.` : "Brak obowiązkowych uzupełnień dla aktualnie aktywnych metod."}</span></span><ChevronDown className="size-5 text-slate-500" /></summary>
      <form action={saveCompanyMethodInputs} className="border-t border-white/[0.08] p-5">
        <input type="hidden" name="analysis_id" value={analysisId} />
        <div className="grid gap-6 xl:grid-cols-2">
          <Fieldset title="OWAS"><NumberField name="owas_load_kg" label="Masa przedmiotu [kg]" /><SelectField name="owas_forced_posture" label="Charakter pozycji" options={[["", "Nie określono"], ["forced", "Wymuszona"], ["unforced", "Niewymuszona"]]} /></Fieldset>
          <Fieldset title="EJMS — dane obszarów"><p className="text-xs leading-5 text-slate-500">Siła nie jest estymowana z filmu. Częstotliwość wpisz tylko wtedy, gdy automatyczne zliczenie zdarzeń nie jest dostępne lub wymaga korekty.</p><div className="grid gap-3 sm:grid-cols-2">{ejmsForceAreas.map(([id, label]) => <div key={id} className="rounded-xl border border-white/[0.07] p-3"><SelectField name={`ejms_force_${id}`} label={`${label} — siła/postawa`} options={ejmsForceOptions} /><div className="mt-3"><NumberField name={`ejms_frequency_${id}`} label="Częstotliwość [/min]" /></div></div>)}</div></Fieldset>
          <Fieldset title="EJMS — dźwiganie i przenoszenie"><div className="grid gap-3 sm:grid-cols-2"><NumberField name="ejms_weight_kg" label="Masa [kg]" /><NumberField name="ejms_horizontal_distance_cm" label="HD [cm]" /><NumberField name="ejms_start_hand_height_from_waist_cm" label="SLH [cm]" /><NumberField name="ejms_vertical_travel_cm" label="Przemieszczenie pionowe [cm]" /><NumberField name="ejms_frequency_per_minute" label="Częstotliwość [/min]" /><NumberField name="ejms_twist_deg" label="Skręt [°]" /><NumberField name="ejms_distance_m" label="Dystans [m]" /><SelectField name="ejms_grip" label="Chwyt" options={[["", "Nie określono"], ["GOOD", "Dobry"], ["SATISFACTORY", "Zadowalający"], ["BAD", "Zły"]]} /></div></Fieldset>
          <Fieldset title="Risk Score — manualny"><TextField name="risk_activity" label="Wykonywana czynność" /><TextField name="risk_hazard_source" label="Źródło zagrożenia" /><TextField name="risk_hazard" label="Zagrożenie" list="company-hazards" /><datalist id="company-hazards">{hazardSuggestions.map((item) => <option key={item.id} value={item.label} />)}</datalist><TextField name="risk_effect" label="Skutek" /><TextField name="risk_controls" label="Istniejące środki kontroli" /><div className="grid gap-3 sm:grid-cols-3"><SelectField name="risk_psif" label="pSIF / SIF" options={[["", "Nie określono"], ["none", "Nie"], ["psif", "pSIF"], ["sif", "SIF"]]} /><SelectField name="risk_factor_type" label="Rodzaj czynnika" options={[["", "Nie określono"], ["niebezpieczny", "Niebezpieczny"], ["szkodliwy", "Szkodliwy"], ["uciążliwy", "Uciążliwy"]]} /><SelectField name="risk_work_type" label="Charakter pracy" options={[["", "Nie określono"], ["rutynowa", "Rutynowa"], ["nierutynowa", "Nierutynowa"]]} /></div><div className="grid gap-3 sm:grid-cols-3"><SelectField name="risk_exposure" label="Ekspozycja" options={options(companyMethodSpecs.riskScore.thresholds.exposure)} /><SelectField name="risk_severity" label="Skutki" options={options(companyMethodSpecs.riskScore.thresholds.severity)} /><SelectField name="risk_probability" label="Prawdopodobieństwo" options={options(companyMethodSpecs.riskScore.thresholds.probability)} /></div><p className="text-xs leading-5 text-amber-100/70">Wynik E×S×P jest oznaczony jako znormalizowana interpretacja, ponieważ skoroszyt nie zawiera formuły wartości ryzyka.</p></Fieldset>
          <div className="space-y-6"><Fieldset title="Czynnik mierzalny"><TextField name="measurement_label" label="Nazwa czynnika" /><div className="grid grid-cols-2 gap-3"><NumberField name="measurement" label="Pomiar P" /><NumberField name="measurement_limit" label="Limit Pmax" /></div><DateField name="measurement_updated_at" label="Data aktualizacji dokumentu" /></Fieldset><Fieldset title="Chemia — część manualna"><TextField name="chemical_name" label="Substancja" /><TextField name="chemical_manufacturer" label="Producent" /><TextField name="chemical_h_statements" label="Zwroty H" /><div className="grid gap-3 sm:grid-cols-2"><SelectField name="chemical_hazard_level" label="Poziom zagrożenia" options={[["", "Nie określono"], ["A", "A"], ["B", "B"], ["C", "C"], ["D", "D"], ["E", "E"]]} /><NumberField name="chemical_boiling_point_c" label="Temperatura wrzenia [°C]" /><NumberField name="chemical_working_temperature_c" label="Temperatura robocza [°C]" /><TextField name="chemical_volatility" label="Lotność" /><TextField name="chemical_solid_category" label="Kategoria ciała stałego" /><TextField name="chemical_exposure_time" label="Czas narażenia" /><TextField name="chemical_quantity" label="Ilość" /><TextField name="chemical_risk_level" label="Poziom ryzyka" /><TextField name="chemical_residual_risk_level" label="Ryzyko po działaniach" /></div><label className="flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" name="chemical_safe" className="size-4 accent-emerald-400" /> Produkt sklasyfikowany jako bezpieczny</label><p className="text-xs leading-5 text-slate-500">Bez instrukcji IN.06.13 system nie wyznacza automatycznie poziomu chemicznego.</p></Fieldset></div>
        </div>
        <div className="mt-6 flex justify-end"><SubmitButton /></div>
      </form>
    </details>
  </section>;
}

const ejmsForceAreas = [["neck", "Szyja"], ["arm", "Ramię"], ["trunk", "Tułów"], ["forearm_elbow", "Przedramię / łokieć"], ["wrist", "Nadgarstek"], ["fingers_hands", "Palce / dłonie"], ["legs", "Nogi"], ["static_load", "Obciążenie statyczne"]] as const;
const ejmsForceOptions = [["", "Nie określono"], ["LOW", "Niska"], ["MOD", "Umiarkowana"], ["HIGH", "Wysoka"]] as const;

function MethodCard({ title, icon: Icon, status: value, value: detail }: { title: string; icon: typeof Weight; status: string; value: string }) { const ready = ["AUTOMATIC", "MANUAL"].includes(value); return <article className="rounded-2xl border border-white/[0.08] bg-slate-950/35 p-4"><div className="flex items-start justify-between gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-cyan-300/[0.08]"><Icon className="size-4 text-cyan-300" /></span><span className={`rounded-full px-2 py-1 text-[9px] font-semibold uppercase ${ready ? "bg-emerald-300/10 text-emerald-200" : "bg-amber-300/10 text-amber-200"}`}>{statusLabel(value)}</span></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></article>; }
function Fieldset({ title, children }: { title: string; children: React.ReactNode }) { return <fieldset className="space-y-3 rounded-2xl border border-white/[0.08] bg-slate-950/30 p-4"><legend className="px-2 font-semibold text-slate-200">{title}</legend>{children}</fieldset>; }
function TextField({ name, label, list }: { name: string; label: string; list?: string }) { return <label className="block text-xs font-medium text-slate-400">{label}<input name={name} list={list} className="mt-1.5 min-h-11 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none focus:border-cyan-300/50" /></label>; }
function NumberField({ name, label }: { name: string; label: string }) { return <label className="block text-xs font-medium text-slate-400">{label}<input name={name} inputMode="decimal" className="mt-1.5 min-h-11 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none focus:border-cyan-300/50" /></label>; }
function DateField({ name, label }: { name: string; label: string }) { return <label className="block text-xs font-medium text-slate-400">{label}<input name={name} type="date" className="mt-1.5 min-h-11 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-sm text-white outline-none focus:border-cyan-300/50" /></label>; }
function SelectField({ name, label, options: items }: { name: string; label: string; options: ReadonlyArray<readonly [string, string]> }) { return <label className="block text-xs font-medium text-slate-400">{label}<select name={name} className="mt-1.5 min-h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm text-white outline-none focus:border-cyan-300/50">{items.map(([value, label]) => <option key={`${name}-${value}`} value={value}>{label}</option>)}</select></label>; }
function SubmitButton() { const { pending } = useFormStatus(); return <button disabled={pending} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-300 px-5 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-60"><CheckCircle2 className="size-4" />{pending ? "Przeliczanie…" : "Zapisz i przelicz bez GPU"}</button>; }
function options(items: ReadonlyArray<{ id: string; label: string }>): Array<readonly [string, string]> { return [["", "Wybierz"], ...items.map((item) => [item.id, item.label] as const)]; }
function status(value: Record<string, unknown> | null | undefined) { return typeof value?.status === "string" ? value.status : "REQUIRES_DATA"; }
function statusLabel(value: string) { return ({ AUTOMATIC: "Automatyczna", PARTIAL: "Częściowa", REQUIRES_DATA: "Wymaga danych", MANUAL: "Manualna", UNAVAILABLE: "Niedostępna", SOURCE_ERROR: "Błąd źródła" } as Record<string, string>)[value] ?? "Niepełne dane"; }
function owasSummary(value: Record<string, unknown> | null) { const summary = rec(value?.summary); return typeof summary?.dominant_category === "number" ? `Dominująca kategoria ${summary.dominant_category}` : "Pozycja rozpoznawana; masa może wymagać uzupełnienia"; }
function ejmsSummary(value: Record<string, unknown> | null) { const section = rec(value?.section_i); return typeof section?.score === "number" ? `Sekcja I: ${section.score} pkt; ranking globalny wyłączony` : "Sekcja I + częściowa sekcja transportowa"; }
function riskSummary(value: Record<string, unknown> | null | undefined) { return typeof value?.category === "string" ? value.category : "Wymaga danych kontekstowych"; }
function rec(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function findDominantOwasFrame(value: Record<string, unknown> | null) { if (!Array.isArray(value?.frames)) return null; for (const raw of value.frames) { const item = rec(raw); if (typeof item?.code === "string" && typeof item.category === "number" && typeof item.timestamp_seconds === "number") return { code: item.code, category: item.category, time: item.timestamp_seconds }; } return null; }

function CompanyMethodDetails({ owas, ejms }: { owas: Record<string, unknown> | null; ejms: Record<string, unknown> | null }) {
  const summary = rec(owas?.summary);
  const ratios = rec(summary?.category_ratios);
  const longest = rec(summary?.longest_episode_seconds);
  const areas = rec(rec(ejms?.section_i)?.areas);
  if (!summary && !areas) return null;
  return <div className="mt-4 grid gap-4 xl:grid-cols-2">
    {summary && <article className="rounded-2xl border border-white/[0.08] bg-slate-950/25 p-4"><h3 className="font-semibold">Rozkład OWAS</h3><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{[1, 2, 3, 4].map((category) => <div key={category} className="rounded-xl bg-white/[0.035] p-3"><p className="text-xs text-slate-500">Kategoria {category}</p><p className="mt-1 font-semibold">{percent(ratios?.[String(category)])}</p><p className="text-[11px] text-slate-500">najdłużej {seconds(longest?.[String(category)])}</p></div>)}</div></article>}
    {areas && <article className="rounded-2xl border border-white/[0.08] bg-slate-950/25 p-4"><h3 className="font-semibold">EJMS — Sekcja I</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{ejmsForceAreas.map(([id, label]) => { const area = rec(areas[id]); return <div key={id} className="flex items-center justify-between gap-3 rounded-xl bg-white/[0.035] px-3 py-2 text-xs"><span className="text-slate-400">{label}</span><span className="text-right text-slate-200">{levelLabel(area?.posture_force_level)} / {levelLabel(area?.frequency_duration_level)} · {typeof area?.score === "number" ? `${area.score} pkt` : "niepełne dane"}</span></div>; })}</div></article>}
  </div>;
}
function levelLabel(value: unknown) { return value === "LOW" ? "Niskie" : value === "MOD" ? "Umiarkowane" : value === "HIGH" ? "Wysokie" : "Niepełne"; }
function percent(value: unknown) { return typeof value === "number" ? `${(value * 100).toFixed(1)}%` : "—"; }
function seconds(value: unknown) { return typeof value === "number" ? `${value.toFixed(1)} s` : "—"; }
