import test from "node:test";
import assert from "node:assert/strict";
import { createHuman } from "../anthropometry.ts";
import { createHuman3DState, getHumanJointPositions3d, setHumanJointRotation, setHumanRoot, validateHuman3D } from "../human-3d-model.ts";
import { solveTwoBoneIk3d } from "../ik-3d.ts";
import { applyHandPreset, createHandRig, getFingerJointPositions, gripGeometryForDiameter, setFingerCurl } from "../hand-rig.ts";
import { createPrimitive3d } from "../object-3d-model.ts";
import { getFingertipReachability, getReachabilityResult } from "../reachability-3d.ts";
import { getCollisionResult, getFingerObjectCollisions, getFloorCollisions, getHeldObjectCollisions } from "../collision-3d.ts";
import { attachObjectToHand, attachObjectTwoHanded, getAttachedObjectWorldPosition, releaseObjectFromHand } from "../object-interaction-3d.ts";
import { createBasicTask3d, evaluateBasicTask3d, getMotionPathResult } from "../motion-3d.ts";
import { distance3, v3 } from "../vector3.ts";
import { measureDistance3d, placeHumanAtSeat3d, snapVector3ToGrid, workSurfaceTarget3d } from "../scene-3d-utils.ts";
import { emptyMeasurements, emptySceneState, normalizeSceneState, validateSceneState } from "../schema.ts";

function object3d(id="box", geometry=createPrimitive3d("BOX",v3(0,80,15),{width:30,height:30,depth:30})) { return { id, sourceClass:null,type:"OTHER",name:id,bbox:{x:.2,y:.2,width:.2,height:.2},detectorConfidence:null,source:"USER",status:"USER_ADDED",visible:true,locked:false,measurements:emptyMeasurements(),geometryMeasurements:[],interactionPoints:[],referencePoint:null,geometry3d:geometry,interactionPoints3d:[] }; }

for (const height of [160,175,190]) test(`Digital Human 3D preserves exact ${height} cm stature`,()=>{const human=createHuman(`H${height}`,"#0ea5e9","CUSTOM");human.profile.heightCm=height;human.profile.physicalDimensions={...human.profile.physicalDimensions,statureCm:height};human.human3d=createHuman3DState(human.profile);assert.equal(validateHuman3D(human.profile,human.human3d).heightCm,height)});

test("neutral 3D pose is left/right symmetric",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d);assert.equal(j.leftShoulder.x,-j.rightShoulder.x);assert.equal(j.leftHip.x,-j.rightHip.x);assert.equal(j.leftKnee.y,j.rightKnee.y)});
test("root uses floor constrained centimeters and continuous yaw",()=>{const h=createHuman("A","#fff"),m=setHumanRoot(h.human3d,v3(20,-30,45),387);assert.deepEqual(m.rootPositionCm,v3(20,0,45));assert.equal(m.rootRotationDeg.y,27)});
test("forward kinematics rotates chest descendants without moving pelvis",()=>{const h=createHuman("A","#fff"),before=getHumanJointPositions3d(h.human3d),rotated=setHumanJointRotation(h.human3d,"chest",v3(20,15,0)),after=getHumanJointPositions3d(rotated);assert.deepEqual(after.pelvis,before.pelvis);assert.notDeepEqual(after.head,before.head);assert.notDeepEqual(after.rightWrist,before.rightWrist)});
test("1000 deterministic 3D IK targets remain finite with fixed lengths",()=>{let seed=7;const random=()=>((seed=seed*48271%2147483647)/2147483647);for(let i=0;i<1000;i++){const root=v3(),target=v3((random()-.5)*100,random()*90,(random()-.5)*80),result=solveTwoBoneIk3d(root,target,v3(0,40,30),35,30);assert.ok(Object.values(result.joint).every(Number.isFinite));assert.ok(Math.abs(distance3(root,result.joint)-35)<1e-6);assert.ok(Math.abs(distance3(result.joint,result.end)-30)<1e-5)}});
test("pole target changes bend plane without changing lengths",()=>{const a=solveTwoBoneIk3d(v3(),v3(50,10,0),v3(0,30,30),35,30),b=solveTwoBoneIk3d(v3(),v3(50,10,0),v3(0,30,-30),35,30);assert.notEqual(Math.sign(a.joint.z),Math.sign(b.joint.z));assert.ok(Math.abs(distance3(a.joint,a.end)-30)<1e-6)});

for (const preset of ["OPEN","CLOSED_FIST","PINCH","CYLINDER_GRIP","SPHERE_GRIP"]) test(`finger preset ${preset} stays connected and finite`,()=>{const h=createHuman("A","#fff"),hand=applyHandPreset(createHandRig(),preset),points=getFingerJointPositions(h.profile,hand,"right",v3());for(const p of Object.values(points))assert.ok(Object.values(p).every(Number.isFinite));for(const finger of ["thumb","index","middle","ring","little"])assert.ok(points[`${finger}TIP`])});
test("manual finger curl is bounded",()=>{const hand=setFingerCurl(createHandRig(),"index",5);assert.equal(hand.fingers.index.curl,1)});
test("small cylinder grip is valid and 25 cm grip is invalid",()=>{const h=createHuman("A","#fff");assert.equal(gripGeometryForDiameter(h.profile,5,"CYLINDER_GRIP").status,"GRIP_GEOMETRY_VALID");assert.equal(gripGeometryForDiameter(h.profile,25,"CYLINDER_GRIP").status,"GRIP_GEOMETRY_INVALID")});

test("reachability distinguishes arm only, whole body and unreachable",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),near=v3(j.rightShoulder.x+30,j.rightShoulder.y,j.rightShoulder.z),body=v3(j.rightShoulder.x+h.profile.physicalDimensions.upperArmLengthCm+h.profile.physicalDimensions.forearmLengthCm+10,j.rightShoulder.y,0),far=v3(300,200,0);assert.notEqual(getReachabilityResult(h,"RIGHT",near).level,"UNREACHABLE");assert.equal(getReachabilityResult(h,"RIGHT",body,"WHOLE_BODY").level,"REACHABLE_WITH_BODY_MOVEMENT");assert.equal(getReachabilityResult(h,"RIGHT",far,"WHOLE_BODY").level,"UNREACHABLE")});
test("reach margin is positive inside and negative outside",()=>{const h=createHuman("A","#fff"),s=getHumanJointPositions3d(h.human3d).rightShoulder;assert.ok(getReachabilityResult(h,"RIGHT",v3(s.x+20,s.y,s.z)).reachMarginCm>0);assert.ok(getReachabilityResult(h,"RIGHT",v3(s.x+200,s.y,s.z)).reachMarginCm<0)});
test("index fingertip exists for button targeting",()=>{const h=createHuman("A","#fff"),p=getFingerJointPositions(h.profile,h.human3d.hands.right,"right",getHumanJointPositions3d(h.human3d).rightWrist);assert.ok(p.indexTIP);assert.ok(distance3(p.indexMCP,p.indexTIP)>0)});
test("button task uses fingertip reach and transparent task result",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),target=v3(j.rightShoulder.x+40,j.rightShoulder.y,0),reach=getFingertipReachability(h,"RIGHT",target,"button");assert.notEqual(reach.level,"UNREACHABLE");const task=createBasicTask3d("PRESS_BUTTON",h,"RIGHT",j.rightWrist,target,null,"button"),result=evaluateBasicTask3d(task,h,[]);assert.equal(result.status,"FEASIBLE");assert.equal(result.reachability.reasons[0],"index_fingertip_target")});

test("unknown depth returns UNKNOWN_GEOMETRY instead of CLEAR",()=>{const h=createHuman("A","#fff"),o=object3d("plane",{...createPrimitive3d("BOX"),dimensionsCm:{width:20,height:20,depth:null,diameter:null,length:null},geometryQuality:"PARTIAL",collisionEnabled:false});assert.equal(getCollisionResult(h,o)[0].level,"UNKNOWN_GEOMETRY")});
test("arm and box penetration is detected",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),o=object3d("arm-box",createPrimitive3d("BOX",j.rightElbow,{width:20,height:20,depth:20}));assert.ok(getCollisionResult(h,o).some((r)=>r.level==="PENETRATION"||r.level==="CONTACT"))});
test("high detail finger collision detects fingertip against a button",()=>{const h=createHuman("A","#fff"),wrist=getHumanJointPositions3d(h.human3d).rightWrist,points=getFingerJointPositions(h.profile,h.human3d.hands.right,"right",wrist),button=object3d("button",createPrimitive3d("BOX",points.indexTIP,{width:2,height:2,depth:2}));assert.ok(getFingerObjectCollisions(h,button,"RIGHT").some((r)=>r.level==="PENETRATION"||r.level==="CONTACT"))});
test("floor collision is explicit when a body proxy crosses Y zero",()=>{const h=createHuman("A","#fff"),lowered={...h,human3d:{...h.human3d,rootPositionCm:v3(0,-30,0)}};assert.ok(getFloorCollisions(lowered).some((result)=>result.objectId==="scene-floor"))});
test("held object collision is detected against shelf",()=>{const held=object3d("held",createPrimitive3d("BOX",v3(0,100,0),{width:30,height:30,depth:30})),shelf=object3d("shelf",createPrimitive3d("BOX",v3(10,100,0),{width:30,height:30,depth:30})),h=createHuman("A","#fff");assert.equal(getHeldObjectCollisions(h,held,[shelf])[0].level,"PENETRATION")});
test("grip attachment follows hand relation and release preserves object world transform",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),o=object3d("tool",createPrimitive3d("CYLINDER",j.rightWrist,{diameter:5,length:15}));o.interactionPoints3d=[{id:"grip",name:"Grip",type:"GRIP",positionCm:j.rightWrist,rotationDeg:v3(),hand:"RIGHT"}];const attached=attachObjectToHand(h,o,"RIGHT","CYLINDER_GRIP");assert.equal(attached.human.human3d.attachments.rightObjectId,o.id);const released=releaseObjectFromHand(attached.human,attached.object,"RIGHT");assert.equal(released.human.human3d.attachments.rightObjectId,null);assert.deepEqual(released.object.geometry3d.positionCm,o.geometry3d.positionCm)});
test("attached object follows moved hand and release keeps resolved world position",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),o=object3d("tool-follow",createPrimitive3d("CYLINDER",j.rightWrist,{diameter:5,length:15}));o.interactionPoints3d=[{id:"grip",name:"Grip",type:"GRIP",positionCm:j.rightWrist,rotationDeg:v3(),hand:"RIGHT"}];const attached=attachObjectToHand(h,o,"RIGHT","CYLINDER_GRIP"),moved={...attached.human,human3d:setHumanRoot(attached.human.human3d,v3(30,0,20))},world=getAttachedObjectWorldPosition(moved,attached.object);assert.equal(world.x,j.rightWrist.x+30);assert.equal(world.z,j.rightWrist.z+20);const released=releaseObjectFromHand(moved,attached.object,"RIGHT");assert.deepEqual(released.object.geometry3d.positionCm,world)});
test("two hand grip requires two reachable grip points",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),o=object3d("bar",createPrimitive3d("HANDLE",v3(0,j.leftWrist.y,0),{diameter:4,length:40}));o.interactionPoints3d=[{id:"l",name:"L",type:"GRIP",positionCm:j.leftWrist,rotationDeg:v3(),hand:"LEFT"},{id:"r",name:"R",type:"GRIP",positionCm:j.rightWrist,rotationDeg:v3(),hand:"RIGHT"}];assert.equal(attachObjectTwoHanded(h,o).human.human3d.attachments.rightObjectId,o.id)});
test("motion path reports first collision progress",()=>{const h=createHuman("A","#fff"),j=getHumanJointPositions3d(h.human3d),start=j.rightWrist,target=v3(start.x+20,start.y,start.z),obstacle=object3d("path",createPrimitive3d("BOX",v3((start.x+target.x)/2,start.y,start.z),{width:8,height:20,depth:20})),result=getMotionPathResult(h,[obstacle],"RIGHT",start,target,24);assert.equal(result.status,"COLLISION");assert.ok(result.firstCollisionProgress!==null)});
test("3D measurement and grid snapping use centimeters",()=>{assert.equal(measureDistance3d(v3(),v3(3,4,12)),13);assert.deepEqual(snapVector3ToGrid(v3(12,-2,27),5),v3(10,0,25))});
test("seat and work surface helpers require complete vertical geometry",()=>{const h=createHuman("A","#fff"),seat=object3d("seat",createPrimitive3d("BOX",v3(10,25,30),{width:40,height:50,depth:40})),placed=placeHumanAtSeat3d(h,seat),target=workSurfaceTarget3d(seat,5);assert.equal(placed.status,"PLACED");assert.equal(placed.human.placement.positionMode,"SEATED_AT_OBJECT");assert.deepEqual(target,v3(15,50,30));assert.equal(workSurfaceTarget3d({...seat,geometry3d:null}),null)});

test("schema 1.3 migrates to 1.4 with 2D backup and serializable physical state",()=>{const scene=emptySceneState(),human=createHuman("Legacy","#fff");const legacy=structuredClone(scene);legacy.schema_version="1.3";delete legacy.scene3d;delete human.human3d;legacy.humans=[human];const normalized=normalizeSceneState(legacy);assert.equal(normalized.schema_version,"1.4");assert.equal(normalized.humans[0].human3d.migrationStatus,"MIGRATED_TO_3D");assert.ok(normalized.humans[0].human3d.legacy2dBackup);assert.equal(validateSceneState(JSON.parse(JSON.stringify(normalized))),true)});
