"use client";

import { estimateLocalScale } from "@/lib/photo-scene/calibration";
import { renderedHeightPixels } from "@/lib/photo-scene/anthropometry";
import type { HumanJointName, ReachDisplayMode, SceneCalibration, SceneHuman } from "@/types/photo-scene";

export type HumanDragKind = "HUMAN_ROOT" | "STANDING" | "JOINT" | "ORIENTATION";

export function HumanMannequin({ human, width, height, calibration, selected, reachVisible, reachMode, debug, zoom, onStart, onSelect }: {
  human: SceneHuman; width: number; height: number; calibration: SceneCalibration; selected: boolean;
  reachVisible: boolean; reachMode: ReachDisplayMode; debug: boolean; zoom: number;
  onStart: (kind: HumanDragKind, joint: HumanJointName | undefined, event: React.PointerEvent<SVGElement>) => void;
  onSelect: () => void;
}) {
  const j = human.pose.joints, scale = estimateLocalScale(calibration, human.placement.contactPoint, width, height);
  const pxPerCm = scale?.pixelsPerCm ?? human.placement.lastScalePxPerCm ?? Math.max(1, renderedHeightPixels(human.pose, height) / human.profile.heightCm);
  const torsoTop = midpoint(j.leftShoulder, j.rightShoulder), renderedCm = renderedHeightPixels(human.pose, height) / pxPerCm;
  const reachCm = reachMode === "COMFORT" ? human.profile.functionalReachCm : reachMode === "FUNCTIONAL" ? human.profile.maximumReachCm * .9 : human.profile.maximumReachCm;
  const reachStyle = reachMode === "COMFORT" ? { dash: undefined, opacity: .055 } : reachMode === "FUNCTIONAL" ? { dash: "9 7", opacity: .04 } : { dash: "3 8", opacity: .025 };
  const editable = selected && zoom >= .8;
  const handleJoints: HumanJointName[] = ["leftShoulder", "rightShoulder", "leftElbow", "rightElbow", "leftWrist", "rightWrist", "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle"];
  return <g data-human-id={human.id} opacity={human.locked ? .72 : 1} onPointerDown={(event) => { event.stopPropagation(); onSelect(); }}>
    {reachVisible && selected && [j.leftShoulder, j.rightShoulder].map((shoulder, index) => <circle key={index} cx={shoulder.x * width} cy={shoulder.y * height} r={reachCm * pxPerCm} fill={withAlpha(human.color, reachStyle.opacity)} stroke={human.color} strokeOpacity=".42" strokeWidth="1.5" strokeDasharray={reachStyle.dash} pointerEvents="none" />)}
    <TaperedSegment a={j.neck} b={torsoTop} width={width} height={height} proximal={human.profile.heightCm * .052 * pxPerCm} distal={human.profile.heightCm * .075 * pxPerCm} fill="#273244" accent={human.color} />
    <path d={torsoPath(j.leftShoulder, j.rightShoulder, j.leftHip, j.rightHip, width, height)} fill="#1f2937" stroke={selected ? human.color : "#64748b"} strokeWidth={selected ? 3 : 1.6} onPointerDown={(event) => onStart("HUMAN_ROOT", undefined, event)} />
    <path d={pelvisPath(j.leftHip, j.rightHip, j.pelvisRoot, width, height)} fill="#111827" stroke={human.color} strokeOpacity=".72" strokeWidth="2" onPointerDown={(event) => onStart("HUMAN_ROOT", undefined, event)} />
    <TaperedSegment a={j.leftShoulder} b={j.leftElbow} width={width} height={height} proximal={human.constraints.upperArm.proximalWidthCm * pxPerCm} distal={human.constraints.upperArm.distalWidthCm * pxPerCm} fill="#253044" accent={human.color} />
    <TaperedSegment a={j.rightShoulder} b={j.rightElbow} width={width} height={height} proximal={human.constraints.upperArm.proximalWidthCm * pxPerCm} distal={human.constraints.upperArm.distalWidthCm * pxPerCm} fill="#253044" accent={human.color} />
    <TaperedSegment a={j.leftElbow} b={j.leftWrist} width={width} height={height} proximal={human.constraints.forearm.proximalWidthCm * pxPerCm} distal={human.constraints.forearm.distalWidthCm * pxPerCm} fill="#202b3b" accent={human.color} warning={human.pose.reachState.leftArm === "OUT_OF_REACH"} />
    <TaperedSegment a={j.rightElbow} b={j.rightWrist} width={width} height={height} proximal={human.constraints.forearm.proximalWidthCm * pxPerCm} distal={human.constraints.forearm.distalWidthCm * pxPerCm} fill="#202b3b" accent={human.color} warning={human.pose.reachState.rightArm === "OUT_OF_REACH"} />
    <TaperedSegment a={j.leftHip} b={j.leftKnee} width={width} height={height} proximal={human.constraints.thigh.proximalWidthCm * pxPerCm} distal={human.constraints.thigh.distalWidthCm * pxPerCm} fill="#202b3b" accent={human.color} />
    <TaperedSegment a={j.rightHip} b={j.rightKnee} width={width} height={height} proximal={human.constraints.thigh.proximalWidthCm * pxPerCm} distal={human.constraints.thigh.distalWidthCm * pxPerCm} fill="#202b3b" accent={human.color} />
    <TaperedSegment a={j.leftKnee} b={j.leftAnkle} width={width} height={height} proximal={human.constraints.lowerLeg.proximalWidthCm * pxPerCm} distal={human.constraints.lowerLeg.distalWidthCm * pxPerCm} fill="#1b2534" accent={human.color} warning={human.pose.reachState.leftLeg === "OUT_OF_REACH"} />
    <TaperedSegment a={j.rightKnee} b={j.rightAnkle} width={width} height={height} proximal={human.constraints.lowerLeg.proximalWidthCm * pxPerCm} distal={human.constraints.lowerLeg.distalWidthCm * pxPerCm} fill="#1b2534" accent={human.color} warning={human.pose.reachState.rightLeg === "OUT_OF_REACH"} />
    <Hand a={j.leftWrist} b={j.leftHand} width={width} height={height} size={human.constraints.hand.distalWidthCm * pxPerCm} color={human.color} /><Hand a={j.rightWrist} b={j.rightHand} width={width} height={height} size={human.constraints.hand.distalWidthCm * pxPerCm} color={human.color} />
    <Foot ankle={j.leftAnkle} toe={j.leftFoot} width={width} height={height} size={human.constraints.foot.distalWidthCm * pxPerCm} color={human.color} /><Foot ankle={j.rightAnkle} toe={j.rightFoot} width={width} height={height} size={human.constraints.foot.distalWidthCm * pxPerCm} color={human.color} />
    <Head top={j.head} neck={j.neck} width={width} height={height} humanHeightPx={human.profile.heightCm * pxPerCm} color={human.color} />
    {selected && <line x1={human.placement.contactPoint.x * width} y1={human.placement.contactPoint.y * height} x2={j.head.x * width} y2={j.head.y * height} stroke={human.color} strokeOpacity=".38" strokeDasharray="5 7" pointerEvents="none" />}
    {selected && <text x={j.head.x * width + 9} y={j.head.y * height + 13} fill={human.color} fontSize="12" fontWeight="700">{human.profile.heightCm.toFixed(0)} cm</text>}
    {editable && handleJoints.map((name) => <circle key={name} cx={j[name].x * width} cy={j[name].y * height} r={Math.max(5, 7 / Math.max(.8, zoom))} fill="white" stroke={human.color} strokeWidth="3" onPointerDown={(event) => onStart("JOINT", name, event)} />)}
    {selected && <g onPointerDown={(event) => onStart("HUMAN_ROOT", "pelvisRoot", event)}><circle cx={j.pelvisRoot.x * width} cy={j.pelvisRoot.y * height} r="9" fill={human.color} stroke="white" strokeWidth="2" /><path d={`M${j.pelvisRoot.x * width - 4} ${j.pelvisRoot.y * height}h8M${j.pelvisRoot.x * width} ${j.pelvisRoot.y * height - 4}v8`} stroke="white" /></g>}
    {selected && <g onPointerDown={(event) => onStart("STANDING", undefined, event)}><circle cx={human.placement.contactPoint.x * width} cy={human.placement.contactPoint.y * height} r="10" fill="#0f172a" stroke={human.color} strokeWidth="3" /><circle cx={human.placement.contactPoint.x * width} cy={human.placement.contactPoint.y * height} r="3" fill="white" /><text x={human.placement.contactPoint.x * width + 13} y={human.placement.contactPoint.y * height + 4} fill="white" fontSize="11">Punkt stania</text></g>}
    {selected && <g onPointerDown={(event) => onStart("ORIENTATION", undefined, event)}><line x1={human.placement.contactPoint.x * width} y1={human.placement.contactPoint.y * height} x2={human.placement.contactPoint.x * width + Math.cos(human.placement.orientationDeg * Math.PI / 180) * 42} y2={human.placement.contactPoint.y * height + Math.sin(human.placement.orientationDeg * Math.PI / 180) * 42} stroke={human.color} strokeWidth="3" markerEnd="url(#facing-arrow)" /></g>}
    {selected && (human.pose.reachState.leftArm === "OUT_OF_REACH" || human.pose.reachState.rightArm === "OUT_OF_REACH") && <text x={j.neck.x * width + 12} y={j.neck.y * height - 10} fill="#f59e0b" fontSize="12" fontWeight="700">Poza maksymalnym zasięgiem</text>}
    {debug && <g pointerEvents="none"><rect x={j.pelvisRoot.x * width + 18} y={j.pelvisRoot.y * height - 62} width="210" height="58" rx="6" fill="rgba(2,6,23,.9)" /><text x={j.pelvisRoot.x * width + 27} y={j.pelvisRoot.y * height - 44} fill="#67e8f9" fontSize="11">Expected: {human.profile.heightCm.toFixed(1)} cm</text><text x={j.pelvisRoot.x * width + 27} y={j.pelvisRoot.y * height - 28} fill="#67e8f9" fontSize="11">Rendered: {renderedCm.toFixed(1)} cm · {pxPerCm.toFixed(2)} px/cm</text><text x={j.pelvisRoot.x * width + 27} y={j.pelvisRoot.y * height - 12} fill="#67e8f9" fontSize="11">Scale: {scale?.status ?? "NO_SCALE"}</text></g>}
  </g>;
}

function TaperedSegment({ a, b, width, height, proximal, distal, fill, accent, warning = false }: { a: { x: number; y: number }; b: { x: number; y: number }; width: number; height: number; proximal: number; distal: number; fill: string; accent: string; warning?: boolean }) { const p = segmentPolygon(a, b, width, height, proximal, distal); return <g pointerEvents="none"><polygon points={p} fill={fill} stroke={warning ? "#f59e0b" : "#475569"} strokeWidth="1.2" strokeLinejoin="round" /><line x1={a.x * width} y1={a.y * height} x2={b.x * width} y2={b.y * height} stroke={warning ? "#f59e0b" : accent} strokeOpacity=".52" strokeWidth="1.5" /></g>; }
function Hand({ a, b, width, height, size, color }: { a: { x: number; y: number }; b: { x: number; y: number }; width: number; height: number; size: number; color: string }) { const angle = Math.atan2((b.y - a.y) * height, (b.x - a.x) * width) * 180 / Math.PI; return <ellipse cx={b.x * width} cy={b.y * height} rx={Math.max(5, size * 1.15)} ry={Math.max(3, size * .68)} transform={`rotate(${angle} ${b.x * width} ${b.y * height})`} fill="#172033" stroke={color} strokeWidth="1.5" />; }
function Foot({ ankle, toe, width, height, size, color }: { ankle: { x: number; y: number }; toe: { x: number; y: number }; width: number; height: number; size: number; color: string }) { const angle = Math.atan2((toe.y - ankle.y) * height, (toe.x - ankle.x) * width) * 180 / Math.PI, cx = (ankle.x + toe.x) / 2 * width, cy = (ankle.y + toe.y) / 2 * height; return <rect x={cx - Math.max(8, Math.abs((toe.x - ankle.x) * width) / 2)} y={cy - Math.max(3, size * .38)} width={Math.max(16, Math.abs((toe.x - ankle.x) * width))} height={Math.max(7, size * .76)} rx={Math.max(3, size * .35)} transform={`rotate(${angle} ${cx} ${cy})`} fill="#111827" stroke={color} strokeWidth="1.5" />; }
function Head({ top, neck, width, height, humanHeightPx, color }: { top: { x: number; y: number }; neck: { x: number; y: number }; width: number; height: number; humanHeightPx: number; color: string }) { const headHeight = humanHeightPx * .115, centerY = top.y * height + headHeight / 2; return <g><ellipse cx={top.x * width} cy={centerY} rx={headHeight * .36} ry={headHeight * .5} fill="#263244" stroke={color} strokeWidth="2" /><path d={`M${top.x * width - headHeight * .25} ${centerY + headHeight * .22}Q${top.x * width} ${centerY + headHeight * .48} ${top.x * width + headHeight * .25} ${centerY + headHeight * .22}`} fill="none" stroke="#94a3b8" strokeOpacity=".55" /><line x1={top.x * width} y1={centerY + headHeight * .5} x2={neck.x * width} y2={neck.y * height} stroke="#263244" strokeWidth={headHeight * .26} strokeLinecap="round" /></g>; }
function segmentPolygon(a: { x: number; y: number }, b: { x: number; y: number }, width: number, height: number, proximal: number, distal: number) { const ax = a.x * width, ay = a.y * height, bx = b.x * width, by = b.y * height, length = Math.max(.001, Math.hypot(bx - ax, by - ay)), nx = -(by - ay) / length, ny = (bx - ax) / length; return `${ax + nx * proximal / 2},${ay + ny * proximal / 2} ${bx + nx * distal / 2},${by + ny * distal / 2} ${bx - nx * distal / 2},${by - ny * distal / 2} ${ax - nx * proximal / 2},${ay - ny * proximal / 2}`; }
function torsoPath(ls: { x: number; y: number }, rs: { x: number; y: number }, lh: { x: number; y: number }, rh: { x: number; y: number }, width: number, height: number) { const waistLeft = { x: lh.x - (rs.x - ls.x) * .06, y: (lh.y + ls.y) / 2 }, waistRight = { x: rh.x + (rs.x - ls.x) * .06, y: (rh.y + rs.y) / 2 }; return `M${ls.x * width},${ls.y * height} Q${waistLeft.x * width},${waistLeft.y * height} ${lh.x * width},${lh.y * height} L${rh.x * width},${rh.y * height} Q${waistRight.x * width},${waistRight.y * height} ${rs.x * width},${rs.y * height}Z`; }
function pelvisPath(lh: { x: number; y: number }, rh: { x: number; y: number }, root: { x: number; y: number }, width: number, height: number) { return `M${lh.x * width},${(lh.y - .012) * height} Q${root.x * width},${(root.y + .035) * height} ${rh.x * width},${(rh.y - .012) * height} L${rh.x * width},${(rh.y + .025) * height} Q${root.x * width},${(root.y + .055) * height} ${lh.x * width},${(lh.y + .025) * height}Z`; }
function midpoint(a: { x: number; y: number }, b: { x: number; y: number }) { return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }; }
function withAlpha(hex: string, opacity: number) { if (!hex.startsWith("#") || hex.length !== 7) return hex; return `${hex}${Math.round(opacity * 255).toString(16).padStart(2, "0")}`; }
