"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Calculator, FileText, GitCompare, LoaderCircle, Save, Sparkles } from "lucide-react";
import type { SceneState } from "@/types/photo-scene";
import { buildSceneErgonomicsInput, hashSceneState } from "@/lib/scene-ergonomics/input";
import { assessScene, assessmentStatus } from "@/lib/scene-ergonomics/processor";
import { compareVariant, evaluateVariant } from "@/lib/scene-ergonomics/variants";
import { generateReachHeatmap } from "@/lib/scene-ergonomics/workspace";
import { sceneErgonomicsGeometryGate } from "@/lib/photo-scene/scene-reconstruction";
import { emptyManualContext, type BodyRegion, type SceneAssessmentResult, type SceneManualContext, type SceneTaskSequence, type WorkTaskType } from "@/lib/scene-ergonomics/types";

type Props={analysisId:string;state:SceneState;selectedHumanId:string|null;focus:(humanId:string,objectId:string|null,region:BodyRegion|null)=>void};
const inputClass="w-full rounded-lg border border-border bg-card px-3 py-2 text-xs text-foreground outline-none focus:border-primary";

export function SceneErgonomicsPanel({analysisId,state,selectedHumanId,focus}:Props){
  const[manual,setManual]=useState<SceneManualContext>(emptyManualContext),[task,setTask]=useState<SceneTaskSequence|null>(null),[assessment,setAssessment]=useState<SceneAssessmentResult|null>(null),[saved,setSaved]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState<string|null>(null),[variantDelta,setVariantDelta]=useState(-15),[comparison,setComparison]=useState<ReturnType<typeof compareVariant>|null>(null);
  const revision=useMemo(()=>hashSceneState(state),[state]),input=useMemo(()=>buildSceneErgonomicsInput(analysisId,state,{manualContext:manual,task}),[analysisId,state,manual,task]),geometryGate=useMemo(()=>sceneErgonomicsGeometryGate(state),[state]);
  const humanId=selectedHumanId&&input.humans.some((human)=>human.id===selectedHumanId)?selectedHumanId:input.humans[0]?.id??null,human=humanId&&assessment?.humans[humanId]||null,status=assessment?assessmentStatus(assessment,revision):null;
  useEffect(()=>{let active=true;fetch(`/api/photo-scenes/${analysisId}/assessment`).then((response)=>response.ok?response.json():null).then((data:unknown)=>{const parsed=data as{assessment?:SceneAssessmentResult|null}|null;if(active&&parsed?.assessment){setAssessment(parsed.assessment);setSaved(true)}}).catch(()=>undefined);return()=>{active=false}},[analysisId]);
  useEffect(()=>{if(!geometryGate.allowed||!assessment||assessment.sceneRevision===revision)return;const timer=window.setTimeout(()=>{try{setAssessment(assessScene(input));setSaved(false);setMessage("Podgląd przeliczono po zmianie sceny. Zapisz, aby utrwalić wynik.")}catch{/* invalid draft remains stale */}},500);return()=>window.clearTimeout(timer)},[assessment,geometryGate.allowed,input,revision]);
  function calculate(){if(!geometryGate.allowed){setMessage(geometryGate.reasons[0]);return}try{setAssessment(assessScene(input));setSaved(false);setComparison(null);setMessage("Ocena aktualnej pozycji została przeliczona.")}catch(error){setMessage(error instanceof Error?error.message:"Nie udało się obliczyć oceny.")}}
  async function save(){if(!geometryGate.allowed){setMessage(geometryGate.reasons[0]);return}setLoading(true);setMessage(null);const sceneResponse=await fetch(`/api/photo-scenes/${analysisId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({scene_state:state})});if(!sceneResponse.ok){setMessage("Najpierw nie udało się zapisać aktualnego stanu sceny.");setLoading(false);return}const response=await fetch(`/api/photo-scenes/${analysisId}/assessment`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({task,manual_context:manual})});const payload=await response.json().catch(()=>null) as{assessment?:SceneAssessmentResult;error?:string}|null;if(response.ok&&payload?.assessment){setAssessment(payload.assessment);setSaved(true);setMessage("Ocena i Scene Design Report zostały zapisane w prywatnym Storage.")}else setMessage(payload?.error??"Nie udało się zapisać oceny.");setLoading(false)}
  function createTask(){const object=input.objects.find((item)=>item.interactionPoints.length),point=object?.interactionPoints[0];if(!humanId||!object||!point){setMessage("Dodaj punkt interakcji 3D, aby utworzyć sekwencję zadania.");return}setTask({id:crypto.randomUUID(),name:"Sekwencja robocza",steps:["REACH","GRASP","MOVE_OBJECT","PLACE","RETURN"].map((type,index)=>({id:crypto.randomUUID(),type:type as SceneTaskSequence["steps"][number]["type"],humanId,hand:point.hand==="LEFT"?"LEFT":"RIGHT",targetObjectId:object.id,targetPointId:point.id,startPose:null,endPose:null,durationSeconds:index===0?1:null,repetitions:null}))});setMessage("Utworzono prostą sekwencję. Uzupełnij czas i kontekst, jeśli mają być liczone ekspozycje.")}
  function compare(){const object=input.objects.find((item)=>item.geometry);if(!assessment||!object)return;const variant=evaluateVariant(input,[{type:"OBJECT_POSITION",targetId:object.id,axis:"z",deltaCm:variantDelta}]);setComparison(compareVariant(assessment,variant))}
  const heatmapCount=useMemo(()=>{const operator=input.humans.find((item)=>item.id===humanId),surface=input.objects.find((item)=>["TABLE","WORK_SURFACE","CONTROL_PANEL"].includes(item.type));return operator&&surface?generateReachHeatmap(operator,surface,"BOTH",15).length:0},[humanId,input]);
  if(!input.humans.length)return <Info text="Dodaj i pokaż operatora 3D, aby uruchomić Scene Ergonomics Engine."/>;
  return <div className="space-y-4">
    <div className="rounded-xl border border-cyan-500/30 bg-cyan-500/5 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-600">Scene Ergonomics V1</p><strong className="text-sm">Techniczna ocena projektu</strong></div>{status&&<Badge value={status}/>}</div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">Wyniki pochodzą z fizycznego modelu 3D. Nie są certyfikacją ani decyzją BHP.</p></div>
    {!geometryGate.allowed&&<Info text={geometryGate.reasons[0]??"Geometria sceny wymaga przeliczenia."}/>}<div className="grid grid-cols-2 gap-2"><button onClick={calculate} disabled={!geometryGate.allowed} className="ui-button-primary justify-center disabled:cursor-not-allowed disabled:opacity-40"><Calculator className="size-4"/>Oceń pozycję</button><button onClick={save} disabled={loading||!geometryGate.allowed} className="ui-button-secondary justify-center disabled:opacity-50">{loading?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}Zapisz wynik</button></div>{message&&<p role="status" className="rounded-lg bg-muted p-2 text-xs">{message}</p>}
    {saved && <Link href={`/panel/analizy/${analysisId}/scena/raport`} className="ui-button-secondary w-full justify-center"><FileText className="size-4"/>Otwórz jasny raport do druku</Link>}
    <details className="rounded-xl border border-border p-3"><summary className="cursor-pointer text-sm font-bold">Dane zadania</summary><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs font-semibold">Rodzaj pracy<select value={manual.taskType} onChange={(event)=>setManual({...manual,taskType:event.target.value as WorkTaskType})} className={`${inputClass} mt-1`}><option value="UNKNOWN">Nieokreślony</option><option value="PRECISION">Precyzyjna</option><option value="LIGHT_WORK">Lekka</option><option value="MODERATE_FORCE">Umiarkowana siła</option><option value="HEAVY_WORK">Ciężka</option></select></label><Numeric label="Czas pozycji [s]" value={manual.postureDurationSeconds} set={(value)=>setManual({...manual,postureDurationSeconds:value})}/><Numeric label="Powtórzenia/min" value={manual.repetitionsPerMinute} set={(value)=>setManual({...manual,repetitionsPerMinute:value})}/><Numeric label="Masa [kg] — tylko użytkownik" value={manual.objectMassKg} set={(value)=>setManual({...manual,objectMassKg:value})}/></div><div className="mt-2 grid grid-cols-2 gap-2"><Numeric label="RULA siła 0–3" value={manual.rulaForceLoad} set={(value)=>setManual({...manual,rulaForceLoad:value})}/><Numeric label="RULA mięśnie 0–1" value={manual.rulaMuscleUse} set={(value)=>setManual({...manual,rulaMuscleUse:value})}/><Numeric label="REBA load 0–3" value={manual.rebaLoadForce} set={(value)=>setManual({...manual,rebaLoadForce:value})}/><Numeric label="REBA coupling 0–3" value={manual.rebaCoupling} set={(value)=>setManual({...manual,rebaCoupling:value})}/><Numeric label="REBA activity 0–3" value={manual.rebaActivity} set={(value)=>setManual({...manual,rebaActivity:value})}/></div></details>
    {!assessment&&<Info text="Uruchom ocenę aktualnej pozycji. Brak danych nigdy nie zostanie zastąpiony wartością 0."/>}
    {assessment&&human&&<><Overview assessment={assessment} human={human}/><Angles angles={human.posture.jointAngles}/><div className="grid grid-cols-2 gap-2"><MethodCard title="RULA lewa" method={human.rula.left}/><MethodCard title="RULA prawa" method={human.rula.right}/><MethodCard title="REBA lewa" method={human.reba.left}/><MethodCard title="REBA prawa" method={human.reba.right}/></div>{human.workHeight&&<Card title="Wysokość robocza"><Line label="Powierzchnia" value={`${format(human.workHeight.surfaceHeightCm.value)} cm`}/><Line label="Łokieć" value={`${format(human.workHeight.elbowHeightCm.value)} cm`}/><Line label="Różnica" value={`${format(human.workHeight.differenceFromElbowCm.value)} cm`}/></Card>}<Card title="Dosiężność"><p className="text-xs text-muted-foreground">Mapa powierzchni: {heatmapCount?`${heatmapCount} próbek geometrycznych`:"brak kompletnej powierzchni"}</p>{human.reach.slice(0,5).map((reach)=><button key={`${reach.pointId}:${reach.hand}`} onClick={()=>focus(reach.humanId,reach.objectId,reach.hand==="LEFT"?"LEFT_ARM":"RIGHT_ARM")} className="mt-2 flex w-full justify-between rounded-lg bg-muted/50 p-2 text-left text-xs"><span>{reach.pointName} · {reach.hand}</span><strong>{reach.zone} · {format(reach.reachMarginCm)} cm</strong></button>)}</Card><Card title="Clearance i kolizje">{human.clearance.filter((item)=>item.level!=="CLEAR").slice(0,6).map((item)=><button key={`${item.objectId}:${item.bodyRegion}`} onClick={()=>focus(item.humanId,item.objectId,item.bodyRegion)} className="mt-2 flex w-full justify-between rounded-lg bg-muted/50 p-2 text-left text-xs"><span>{item.bodyRegion}</span><strong>{item.level} · {format(item.minimumClearanceCm)} cm</strong></button>)}{human.clearance.every((item)=>item.level==="CLEAR")&&<p className="text-xs text-muted-foreground">Brak konfliktów dla kompletnej geometrii.</p>}</Card><Card title="Findings">{assessment.findings.map((finding)=><button key={finding.id} onClick={()=>focus(finding.humanId,finding.objectId,finding.bodyRegion)} className="mt-2 w-full rounded-lg border border-border p-2 text-left"><Badge value={finding.priority}/><p className="mt-1 text-xs">{finding.description}</p></button>)}</Card><Card title="Deterministyczne rekomendacje">{assessment.recommendations.map((item)=><p key={item.id} className="mt-2 rounded-lg bg-muted/50 p-2 text-xs">{item.text}<span className="mt-1 block text-[10px] text-muted-foreground">Powód: {item.reason}</span></p>)}</Card><Card title="Brakujące dane">{assessment.missingData.slice(0,7).map((item)=><p key={item.id} className="mt-2 rounded-lg bg-amber-500/10 p-2 text-xs"><strong>{item.label}</strong><span className="mt-1 block text-muted-foreground">{item.reason}</span></p>)}</Card></>}
    <Card title="Sekwencja zadania"><button onClick={createTask} className="ui-button-secondary w-full justify-center"><Sparkles className="size-4"/>{task?"Odtwórz szablon":"Utwórz Reach → Grasp → Move → Place"}</button>{task&&<p className="mt-2 text-xs text-muted-foreground">{task.steps.length} kroków · ścieżka jest próbkowana, nie tylko start/end.</p>}{assessment?.task?.worstSample&&<p className="mt-2 text-xs">Najgorsza próbka: {assessment.task.worstSample.stepId}, {Math.round(assessment.task.worstSample.progress*100)}%.</p>}</Card>
    {assessment&&<Card title="Wariant projektu"><div className="flex gap-2"><input type="number" value={variantDelta} onChange={(event)=>setVariantDelta(Number(event.target.value))} className={inputClass}/><button onClick={compare} className="ui-button-secondary shrink-0"><GitCompare className="size-4"/>Porównaj ΔZ</button></div>{comparison&&<div className="mt-2 grid grid-cols-2 gap-2 text-xs"><Line label="Current findings" value={String(comparison.current.findings)}/><Line label="Variant findings" value={String(comparison.variant.findings)}/><Line label="Current collisions" value={String(comparison.current.collisions)}/><Line label="Variant collisions" value={String(comparison.variant.collisions)}/></div>}<p className="mt-2 text-[10px] text-muted-foreground">Najkorzystniejszy wynik dotyczy wyłącznie testowanego modelu i jawnych założeń.</p></Card>}
  </div>;
}

function Overview({assessment,human}:{assessment:SceneAssessmentResult;human:SceneAssessmentResult["humans"][string]}){return <Card title="Aktualna pozycja"><div className="grid grid-cols-2 gap-2"><Line label="Odchylenia" value={String(assessment.findings.length)}/><Line label="Jakość" value={assessment.quality.overall}/><Line label="Kolizje" value={String(human.clearance.filter((c)=>c.level==="PENETRATION").length)}/><Line label="Reach" value={human.reach[0]?.zone??"UNKNOWN"}/></div></Card>}
function Angles({angles}:{angles:SceneAssessmentResult["humans"][string]["posture"]["jointAngles"]}){const keys=["trunk_flexion_deg","neck_flexion_deg","left_shoulder_elevation_deg","right_shoulder_elevation_deg","left_elbow_flexion_deg","right_elbow_flexion_deg","left_wrist_flexion_deg","right_wrist_flexion_deg"];return <Card title="Kąty 3D"><div className="grid grid-cols-2 gap-2">{keys.map((key)=><Line key={key} label={key.replaceAll("_"," ")} value={angles[key]?.valid?`${format(angles[key].value)}° · ${angles[key].source}`:"UNKNOWN"}/>)}</div></Card>}
function MethodCard({title,method}:{title:string;method:SceneAssessmentResult["humans"][string]["rula"]["left"]}){return <div className="rounded-xl border border-border p-3"><span className="text-[10px] font-bold uppercase text-muted-foreground">{title}</span><strong className="mt-1 block text-sm">{method.status}</strong><p className="text-xs">{method.score!==null?method.score:method.scoreRange?`${method.scoreRange.min}–${method.scoreRange.max}`:"brak danych"}</p></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-border p-3"><h3 className="text-sm font-bold">{title}</h3><div className="mt-2">{children}</div></section>}
function Line({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-muted/50 p-2"><span className="block text-[9px] uppercase text-muted-foreground">{label}</span><strong className="text-xs">{value}</strong></div>}
function Numeric({label,value,set}:{label:string;value:number|null;set:(value:number|null)=>void}){return <label className="text-xs font-semibold">{label}<input type="number" value={value??""} onChange={(event)=>set(event.target.value===""?null:Number(event.target.value))} className={`${inputClass} mt-1`}/></label>}
function Badge({value}:{value:string}){const tone=value==="CURRENT"||value==="HIGH"?"bg-emerald-500/15 text-emerald-700":value==="STALE"||value==="MEDIUM"?"bg-amber-500/15 text-amber-700":"bg-muted text-muted-foreground";return <span className={`inline-flex rounded-full px-2 py-1 text-[9px] font-bold ${tone}`}>{value}</span>}
function Info({text}:{text:string}){return <div className="rounded-xl border border-dashed border-border p-4 text-xs text-muted-foreground"><AlertTriangle className="mb-2 size-4"/>{text}</div>}
function format(value:number|null){return value===null?"—":value.toFixed(1)}
