"""Pose V6.5 offline self-audit, consensus fusion and bounded repair.

This module is deliberately model-agnostic.  The worker supplies RTMW and hand
hypotheses; the functions below audit them, select hard segments and retain the
best per-joint state.  No model weights are modified and no prediction is
promoted to a measurement merely because it was generated by a later pass.
"""

from __future__ import annotations

import math
from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum
from typing import Any

import numpy as np

from .config import IterativeRefinementConfig
from .temporal_reconstruction import PointSource, TemporalFrame


class PoseAuditInputError(ValueError):
    """Raised when an audit boundary receives an unsupported array contract."""

    def __init__(
        self,
        *,
        field: str,
        actual_shape: tuple[int, ...],
        expected_shape: str,
        frame_index: int | None = None,
    ) -> None:
        location = f" at frame {frame_index}" if frame_index is not None else ""
        super().__init__(
            f"pose audit field {field!r}{location} has shape {actual_shape}; "
            f"expected {expected_shape}"
        )
        self.field = field
        self.actual_shape = actual_shape
        self.expected_shape = expected_shape
        self.frame_index = frame_index


def normalize_joint_age_vector(
    values: object,
    joint_count: int,
    *,
    frame_index: int | None = None,
) -> np.ndarray:
    """Normalize supported prediction-age layouts to one value per joint.

    Contract:
    - canonical input/output: ``(joint,)``;
    - historical coordinate-wise input: ``(joint, 1|2)`` and is reduced with
      the conservative maximum finite age per joint;
    - every other layout is rejected explicitly.  In particular, this helper
      deliberately does not call ``squeeze`` or ``flatten``.
    """

    if joint_count < 0:
        raise ValueError("joint_count cannot be negative")
    return _normalize_joint_numeric_vector(
        values,
        joint_count,
        field="prediction_ages",
        frame_index=frame_index,
    )


def _normalize_joint_numeric_vector(
    values: object,
    joint_count: int,
    *,
    field: str,
    frame_index: int | None,
) -> np.ndarray:
    array = np.asarray(values, dtype=np.float64)
    if array.ndim == 1 and array.shape[0] >= joint_count:
        return array[:joint_count].copy()
    if (
        array.ndim == 2
        and array.shape[0] >= joint_count
        and array.shape[1] in {1, 2}
    ):
        selected = array[:joint_count]
        if selected.shape[1] == 1:
            return selected[:, 0].copy()
        finite = np.isfinite(selected)
        reduced = np.full(joint_count, np.nan, dtype=np.float64)
        available = np.any(finite, axis=1)
        if np.any(available):
            safe = np.where(finite[available], selected[available], -np.inf)
            reduced[available] = np.max(safe, axis=1)
        return reduced
    raise PoseAuditInputError(
        field=field,
        actual_shape=tuple(int(value) for value in array.shape),
        expected_shape=f"({joint_count},), ({joint_count}, 1), or ({joint_count}, 2)",
        frame_index=frame_index,
    )


def normalize_joint_mask(
    values: object,
    joint_count: int,
    *,
    field: str = "joint_mask",
    frame_index: int | None = None,
) -> np.ndarray:
    """Normalize a joint or coordinate mask to canonical ``(joint,)``."""

    if joint_count < 0:
        raise ValueError("joint_count cannot be negative")
    array = np.asarray(values, dtype=bool)
    if array.ndim == 1 and array.shape[0] >= joint_count:
        return array[:joint_count].copy()
    if (
        array.ndim == 2
        and array.shape[0] >= joint_count
        and array.shape[1] in {1, 2}
    ):
        return np.any(array[:joint_count], axis=1)
    raise PoseAuditInputError(
        field=field,
        actual_shape=tuple(int(value) for value in array.shape),
        expected_shape=f"({joint_count},), ({joint_count}, 1), or ({joint_count}, 2)",
        frame_index=frame_index,
    )


class PoseErrorCode(StrEnum):
    LOW_MODEL_CONFIDENCE = "LOW_MODEL_CONFIDENCE"
    TEMPORAL_DISCONTINUITY = "TEMPORAL_DISCONTINUITY"
    JOINT_JUMP = "JOINT_JUMP"
    BONE_LENGTH_ERROR = "BONE_LENGTH_ERROR"
    LEFT_RIGHT_AMBIGUITY = "LEFT_RIGHT_AMBIGUITY"
    OCCLUSION = "OCCLUSION"
    MOTION_BLUR = "MOTION_BLUR"
    HAND_DROPOUT = "HAND_DROPOUT"
    WRIST_DISAGREEMENT = "WRIST_DISAGREEMENT"
    ANGLE_OUTLIER = "ANGLE_OUTLIER"
    TRACKING_UNCERTAINTY = "TRACKING_UNCERTAINTY"
    PREDICTION_TOO_OLD = "PREDICTION_TOO_OLD"
    FLOW_DISAGREEMENT = "FLOW_DISAGREEMENT"
    HARD_FRAME = "HARD_FRAME"
    MODEL_DISAGREEMENT = "MODEL_DISAGREEMENT"
    RECONSTRUCTION_OVERUSE = "RECONSTRUCTION_OVERUSE"
    GRIP_FLICKER = "GRIP_FLICKER"
    PASS2_REGRESSION = "PASS2_REGRESSION"


class Repairability(StrEnum):
    REPAIRABLE = "REPAIRABLE"
    UNCERTAIN = "UNCERTAIN"
    NON_REPAIRABLE = "NON_REPAIRABLE"


DEFAULT_BODY_BONES: tuple[tuple[int, int], ...] = (
    (5, 6), (5, 7), (7, 9), (6, 8), (8, 10), (5, 11), (6, 12),
    (11, 12), (11, 13), (13, 15), (12, 14), (14, 16),
)
COUPLED_JOINT_CHAINS: tuple[tuple[int, int, int], ...] = (
    (5, 7, 9),
    (6, 8, 10),
    (11, 13, 15),
    (12, 14, 16),
)
ANGLE_DEPENDENCIES: tuple[tuple[int, int, int], ...] = (
    (5, 7, 9), (6, 8, 10), (11, 13, 15), (12, 14, 16),
)
SOURCE_TRUST: Mapping[str, float] = {
    PointSource.MEASURED.value: 1.00,
    PointSource.REFINED_MEASUREMENT.value: 0.94,
    PointSource.INTERPOLATED.value: 0.62,
    PointSource.FLOW_TRACKED.value: 0.52,
    PointSource.KINEMATIC_RECONSTRUCTED.value: 0.40,
    PointSource.KINEMATIC_PREDICTED.value: 0.20,
    PointSource.REJECTED.value: 0.0,
    PointSource.MISSING.value: 0.0,
}


@dataclass(frozen=True)
class PoseError:
    frame_index: int
    code: PoseErrorCode
    joint_indexes: tuple[int, ...]
    severity: float
    repairable: bool = True
    error_confidence: float = 1.0

    @property
    def repairability(self) -> Repairability:
        if not self.repairable:
            return Repairability.NON_REPAIRABLE
        if self.error_confidence < 0.65:
            return Repairability.UNCERTAIN
        return Repairability.REPAIRABLE

    def to_dict(self) -> dict[str, object]:
        return {
            "frame_index": self.frame_index,
            "code": self.code.value,
            "joint_indexes": list(self.joint_indexes),
            "severity": round(float(np.clip(self.severity, 0.0, 1.0)), 6),
            "error_confidence": round(
                float(np.clip(self.error_confidence, 0.0, 1.0)), 6
            ),
            "repairable": self.repairable,
            "repairability": self.repairability.value,
        }


@dataclass(frozen=True)
class FrameAudit:
    frame_index: int
    quality_score: float
    measurement_coverage: float
    mean_joint_confidence: float
    temporal_consistency: float
    anatomy_quality: float
    tracking_quality: float
    hand_quality: float
    reconstruction_usage: float
    renderer_fallback_usage: float
    errors: tuple[PoseError, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "frame_index": self.frame_index,
            "quality_score": round(self.quality_score, 6),
            "measurement_coverage": round(self.measurement_coverage, 6),
            "mean_joint_confidence": round(self.mean_joint_confidence, 6),
            "temporal_consistency": round(self.temporal_consistency, 6),
            "anatomy_quality": round(self.anatomy_quality, 6),
            "tracking_quality": round(self.tracking_quality, 6),
            "hand_quality": round(self.hand_quality, 6),
            "reconstruction_usage": round(self.reconstruction_usage, 6),
            "renderer_fallback_usage": round(self.renderer_fallback_usage, 6),
            "errors": [error.to_dict() for error in self.errors],
        }


@dataclass(frozen=True)
class HardSegment:
    start_frame: int
    end_frame: int
    error_codes: tuple[PoseErrorCode, ...]
    affected_joint_indexes: tuple[int, ...]
    quality_score: float
    severity: float
    critical: bool = False

    @property
    def frame_count(self) -> int:
        return self.end_frame - self.start_frame + 1

    def to_dict(self) -> dict[str, object]:
        return {
            "start_frame": self.start_frame,
            "end_frame": self.end_frame,
            "frame_count": self.frame_count,
            "error_codes": [item.value for item in self.error_codes],
            "affected_joint_indexes": list(self.affected_joint_indexes),
            "quality_score": round(self.quality_score, 6),
            "severity": round(self.severity, 6),
            "critical": self.critical,
        }


@dataclass(frozen=True)
class PoseAuditResult:
    frames: tuple[FrameAudit, ...]
    errors: tuple[PoseError, ...]
    hard_segments: tuple[HardSegment, ...]
    quality_score: float
    angle_glitch_frames: tuple[int, ...]
    grip_flicker_frames: tuple[int, ...]

    def frame_quality(self, index: int) -> float:
        return self.frames[index].quality_score

    def to_dict(self, *, include_frame_audit: bool = True) -> dict[str, object]:
        counts = Counter(error.code.value for error in self.errors)
        result: dict[str, object] = {
            "quality_score_version": "pose-quality-v2",
            "quality_score": round(self.quality_score, 6),
            "quality_score_is_accuracy": False,
            "quality_components": [
                "measurement_trust", "temporal_continuity", "bone_consistency",
                "topology", "identity", "angular_continuity",
                "model_agreement", "hand_agreement",
            ],
            "error_count": len(self.errors),
            "error_counts": dict(sorted(counts.items())),
            "hard_segments": [item.to_dict() for item in self.hard_segments],
            "angle_glitch_frames": list(self.angle_glitch_frames),
            "grip_flicker_frames": list(self.grip_flicker_frames),
        }
        if include_frame_audit:
            result["frames"] = [frame.to_dict() for frame in self.frames]
        return result


@dataclass(frozen=True)
class PoseHypothesis:
    points: np.ndarray
    scores: np.ndarray
    source: str
    pass_index: int
    source_trust: float = 0.85


@dataclass(frozen=True)
class ConsensusFusionResult:
    points: np.ndarray
    scores: np.ndarray
    selected_joint_metadata: tuple[dict[str, object], ...]
    corrected_joint_indexes: frozenset[int]
    disagreement_joint_indexes: frozenset[int]


@dataclass(frozen=True)
class IterationDecision:
    accepted: bool
    converged: bool
    rolled_back: bool
    quality_before: float
    quality_after: float
    quality_delta: float
    selected_iteration: int

    def to_dict(self) -> dict[str, object]:
        return {
            "accepted": self.accepted,
            "converged": self.converged,
            "rolled_back": self.rolled_back,
            "quality_score_before": round(self.quality_before, 6),
            "quality_score_after": round(self.quality_after, 6),
            "quality_delta": round(self.quality_delta, 6),
            "selected_iteration": self.selected_iteration,
        }


@dataclass(frozen=True)
class GlobalOptimizationResult:
    frames: list[TemporalFrame]
    frame_diagnostics: list[dict[str, object]]
    summary: dict[str, object]


def audit_pose_sequence(
    points: Sequence[np.ndarray],
    scores: Sequence[np.ndarray],
    body_scales: Sequence[float],
    timestamps: Sequence[float],
    tracking_states: Sequence[str],
    motion_states: Sequence[str],
    scene_cuts: Sequence[bool],
    *,
    config: IterativeRefinementConfig,
    hand_visible: Mapping[str, Sequence[bool]] | None = None,
    hand_quality_values: Mapping[str, Sequence[float]] | None = None,
    grip_states: Mapping[str, Sequence[str]] | None = None,
    motion_blur: Sequence[bool] | None = None,
    prediction_ages: Sequence[np.ndarray] | None = None,
    flow_errors: Sequence[np.ndarray] | None = None,
    wrist_disagreement: Mapping[str, Sequence[bool]] | None = None,
    model_disagreements: Mapping[int, Sequence[int]] | None = None,
    point_sources: Sequence[Sequence[PointSource | str]] | None = None,
    body_joint_count: int = 17,
) -> PoseAuditResult:
    """Build an explicit error map and padded hard segments for one hypothesis.

    Array contract at this boundary:
    ``points[frame]`` is ``(joint, xy)``, ``scores[frame]`` is ``(joint,)``,
    ``prediction_ages[frame]`` and ``flow_errors[frame]`` are canonical
    ``(joint,)`` vectors, and ``point_sources[frame]`` has one item per joint.
    Prediction ages additionally accept the documented historical
    ``(joint, 1|2)`` representation through :func:`normalize_joint_age_vector`.
    """

    count = len(points)
    if not (
        count == len(scores) == len(body_scales) == len(timestamps)
        == len(tracking_states) == len(motion_states) == len(scene_cuts)
    ):
        raise ValueError("pose audit inputs must have equal lengths")
    if count == 0:
        return PoseAuditResult((), (), (), 0.0, (), ())
    for field, values in (
        ("motion_blur", motion_blur),
        ("prediction_ages", prediction_ages),
        ("flow_errors", flow_errors),
        ("point_sources", point_sources),
    ):
        if values is not None and len(values) != count:
            raise PoseAuditInputError(
                field=field,
                actual_shape=(len(values),),
                expected_shape=f"({count}, ...)",
            )
    for field, values in (
        ("hand_visible", hand_visible),
        ("hand_quality_values", hand_quality_values),
        ("grip_states", grip_states),
        ("wrist_disagreement", wrist_disagreement),
    ):
        if values is not None:
            for side, side_values in values.items():
                if len(side_values) != count:
                    raise PoseAuditInputError(
                        field=f"{field}.{side}",
                        actual_shape=(len(side_values),),
                        expected_shape=f"({count},)",
                    )
    arrays = [np.asarray(item, dtype=np.float32) for item in points]
    score_arrays = [np.asarray(item, dtype=np.float32) for item in scores]
    for index, array in enumerate(arrays):
        if array.ndim != 2 or array.shape[1] < 2:
            raise PoseAuditInputError(
                field="points",
                actual_shape=tuple(int(value) for value in array.shape),
                expected_shape="(joint, xy>=2)",
                frame_index=index,
            )
    for index, array in enumerate(score_arrays):
        if array.ndim != 1:
            raise PoseAuditInputError(
                field="scores",
                actual_shape=tuple(int(value) for value in array.shape),
                expected_shape="(joint,)",
                frame_index=index,
            )
    joint_count = min(body_joint_count, *(len(item) for item in score_arrays))
    bone_references = _bone_references(arrays, score_arrays, joint_count)
    angle_glitches = detect_angle_glitches(arrays, score_arrays, scene_cuts=scene_cuts)
    angle_joints = {index: joints for index, joints in angle_glitches.items()}
    grip_flickers: set[int] = set()
    if grip_states is not None:
        for states in grip_states.values():
            grip_flickers.update(detect_grip_flicker(states, scene_cuts=scene_cuts))

    frame_audits: list[FrameAudit] = []
    all_errors: list[PoseError] = []
    for index in range(count):
        frame_scores = score_arrays[index][:joint_count]
        finite_points = np.isfinite(arrays[index][:joint_count]).all(axis=1)
        valid = (frame_scores > 0.0) & finite_points
        coverage = float(np.mean(valid)) if joint_count else 0.0
        errors: list[PoseError] = []
        reconstruction_usage = 0.0
        renderer_fallback_usage = 0.0
        if point_sources is not None:
            source_values = [
                value.value if isinstance(value, PointSource) else str(value)
                for value in point_sources[index][:joint_count]
            ]
            reconstructed = {
                PointSource.INTERPOLATED.value,
                PointSource.FLOW_TRACKED.value,
                PointSource.KINEMATIC_RECONSTRUCTED.value,
            }
            reconstruction_usage = sum(value in reconstructed for value in source_values) / max(1, joint_count)
            renderer_fallback_usage = sum(
                value == PointSource.KINEMATIC_PREDICTED.value for value in source_values
            ) / max(1, joint_count)
            measurement_sources = {
                PointSource.MEASURED.value,
                PointSource.REFINED_MEASUREMENT.value,
            }
            coverage = sum(value in measurement_sources for value in source_values) / max(1, joint_count)
            if reconstruction_usage > 0.25:
                errors.append(PoseError(
                    index,
                    PoseErrorCode.RECONSTRUCTION_OVERUSE,
                    tuple(
                        joint for joint, value in enumerate(source_values)
                        if value in reconstructed
                    ),
                    min(1.0, reconstruction_usage),
                ))
        confidence = float(np.mean(frame_scores[valid])) if np.any(valid) else 0.0
        low_indexes = tuple(int(item) for item in np.flatnonzero((frame_scores < 0.25) | ~finite_points))
        if low_indexes:
            errors.append(PoseError(index, PoseErrorCode.LOW_MODEL_CONFIDENCE, low_indexes, 1.0 - confidence))

        tracking = tracking_states[index].upper()
        tracking_quality = 1.0
        if tracking in {"LOST", "TRACK_LOST"}:
            tracking_quality = 0.0
            errors.append(PoseError(index, PoseErrorCode.OCCLUSION, (), 1.0, repairable=False))
        elif tracking in {"REACQUIRING", "PARTIAL", "OCCLUDED"}:
            tracking_quality = 0.45
            errors.append(PoseError(index, PoseErrorCode.TRACKING_UNCERTAINTY, (), 0.65))

        temporal_quality, temporal_errors = _temporal_errors(
            index, arrays, score_arrays, body_scales, scene_cuts, motion_states, joint_count,
        )
        errors.extend(temporal_errors)
        errors.extend(_side_identity_errors(
            index, arrays, score_arrays, body_scales, scene_cuts, motion_states,
        ))
        anatomy_quality, anatomy_errors = _anatomy_errors(
            index, arrays[index], score_arrays[index], body_scales[index], bone_references,
        )
        errors.extend(anatomy_errors)

        if index in angle_joints:
            errors.append(PoseError(index, PoseErrorCode.ANGLE_OUTLIER, angle_joints[index], 0.85))
        if index in grip_flickers:
            errors.append(PoseError(index, PoseErrorCode.GRIP_FLICKER, (9, 10), 0.75))
        if wrist_disagreement is not None:
            wrist_indexes = tuple(
                9 if side == "left" else 10
                for side, values in wrist_disagreement.items()
                if index < len(values) and bool(values[index])
            )
            if wrist_indexes:
                errors.append(PoseError(index, PoseErrorCode.WRIST_DISAGREEMENT, wrist_indexes, 0.70))
        if model_disagreements is not None and index in model_disagreements:
            joints = tuple(sorted(int(value) for value in model_disagreements[index]))
            if joints:
                errors.append(PoseError(
                    index, PoseErrorCode.MODEL_DISAGREEMENT, joints, 0.60,
                    error_confidence=0.60,
                ))
        if motion_blur is not None and bool(motion_blur[index]):
            errors.append(PoseError(index, PoseErrorCode.MOTION_BLUR, (), 0.55))
        if prediction_ages is not None:
            ages = normalize_joint_age_vector(
                prediction_ages[index], joint_count, frame_index=index,
            )
            invalid_age = ~np.isfinite(ages) | (ages < 0.0)
            old_mask = normalize_joint_mask(
                invalid_age | (ages > 0.25),
                joint_count,
                field="prediction_age_old_mask",
                frame_index=index,
            )
            old_indexes = np.flatnonzero(old_mask)
            if old_indexes.size:
                finite_old = ages[old_indexes]
                finite_old = finite_old[np.isfinite(finite_old) & (finite_old >= 0.0)]
                severity = (
                    1.0
                    if np.any(invalid_age[old_indexes]) or finite_old.size == 0
                    else min(1.0, float(np.max(finite_old)))
                )
                errors.append(PoseError(
                    index,
                    PoseErrorCode.PREDICTION_TOO_OLD,
                    tuple(int(item) for item in old_indexes),
                    severity,
                ))
        if flow_errors is not None:
            values = _normalize_joint_numeric_vector(
                flow_errors[index], joint_count,
                field="flow_errors", frame_index=index,
            )
            bad_indexes = np.flatnonzero(np.isfinite(values) & (values > 2.5))
            if bad_indexes.size:
                errors.append(PoseError(
                    index,
                    PoseErrorCode.FLOW_DISAGREEMENT,
                    tuple(int(item) for item in bad_indexes),
                    min(1.0, float(np.max(values[bad_indexes]) / 6.0)),
                ))

        hand_quality = 1.0
        if hand_visible is not None:
            visible = [bool(values[index]) for values in hand_visible.values() if index < len(values)]
            hand_quality = float(np.mean(visible)) if visible else 1.0
            if visible and not all(visible) and tracking_quality > 0.0:
                errors.append(PoseError(index, PoseErrorCode.HAND_DROPOUT, (9, 10), 0.55))
        if hand_quality_values is not None:
            qualities = [
                float(np.clip(values[index], 0.0, 1.0))
                for values in hand_quality_values.values()
                if index < len(values)
            ]
            if qualities:
                hand_quality = min(hand_quality, float(np.mean(qualities)))

        base_quality = float(np.clip(
            0.30 * coverage + 0.20 * confidence + 0.20 * temporal_quality
            + 0.15 * anatomy_quality + 0.10 * tracking_quality + 0.05 * hand_quality,
            0.0, 1.0,
        ))
        penalty_weights = {
            PoseErrorCode.JOINT_JUMP: 0.10,
            PoseErrorCode.TEMPORAL_DISCONTINUITY: 0.06,
            PoseErrorCode.BONE_LENGTH_ERROR: 0.08,
            PoseErrorCode.LEFT_RIGHT_AMBIGUITY: 0.14,
            PoseErrorCode.ANGLE_OUTLIER: 0.12,
            PoseErrorCode.MODEL_DISAGREEMENT: 0.05,
            PoseErrorCode.WRIST_DISAGREEMENT: 0.05,
            PoseErrorCode.RECONSTRUCTION_OVERUSE: 0.08,
        }
        penalty = min(0.42, sum(
            penalty_weights.get(error.code, 0.0) * error.severity
            for error in errors
        ))
        quality = float(np.clip(base_quality - penalty, 0.0, 1.0))
        if quality < 0.64 and tracking_quality > 0.0:
            errors.append(PoseError(index, PoseErrorCode.HARD_FRAME, (), 1.0 - quality))
        deduplicated = _deduplicate_errors(errors)
        all_errors.extend(deduplicated)
        frame_audits.append(FrameAudit(
            index, quality, coverage, confidence, temporal_quality, anatomy_quality,
            tracking_quality, hand_quality, reconstruction_usage,
            renderer_fallback_usage, tuple(deduplicated),
        ))

    hard_segments = group_hard_segments(
        frame_audits,
        timestamps,
        scene_cuts,
        tracking_states,
        padding_seconds=config.segment_padding_seconds,
        maximum_ratio=config.pass2_maximum_ratio,
        minimum_error_confidence=config.minimum_repair_error_confidence,
    )
    quality_score = float(np.mean([item.quality_score for item in frame_audits]))
    return PoseAuditResult(
        tuple(frame_audits), tuple(all_errors), tuple(hard_segments), quality_score,
        tuple(sorted(angle_joints)), tuple(sorted(grip_flickers)),
    )


def detect_angle_glitches(
    points: Sequence[np.ndarray],
    scores: Sequence[np.ndarray],
    *,
    scene_cuts: Sequence[bool] | None = None,
    minimum_spike_degrees: float = 38.0,
) -> dict[int, tuple[int, ...]]:
    """Flag geometry dependencies; never edits a derived angle value."""

    result: dict[int, set[int]] = {}
    count = len(points)
    cuts = scene_cuts or [False] * count
    for first, center, third in ANGLE_DEPENDENCIES:
        values = [_angle(points[index], scores[index], first, center, third) for index in range(count)]
        for index in range(1, count - 1):
            if cuts[index] or cuts[index + 1]:
                continue
            previous, current, following = values[index - 1:index + 2]
            if previous is None or current is None or following is None:
                continue
            baseline = (previous + following) * 0.5
            if abs(previous - following) <= 16.0 and abs(current - baseline) >= minimum_spike_degrees:
                result.setdefault(index, set()).update((first, center, third))
    return {index: tuple(sorted(joints)) for index, joints in result.items()}


def detect_grip_flicker(
    states: Sequence[str], *, scene_cuts: Sequence[bool] | None = None,
) -> tuple[int, ...]:
    cuts = scene_cuts or [False] * len(states)
    suspicious: list[int] = []
    for index in range(1, len(states) - 1):
        if cuts[index] or cuts[index + 1]:
            continue
        previous, current, following = (str(value).upper() for value in states[index - 1:index + 2])
        if previous == following and current != previous and previous not in {"UNKNOWN", "NO_DATA"}:
            suspicious.append(index)
    return tuple(suspicious)


def group_hard_segments(
    frames: Sequence[FrameAudit],
    timestamps: Sequence[float],
    scene_cuts: Sequence[bool],
    tracking_states: Sequence[str],
    *,
    padding_seconds: float,
    maximum_ratio: float,
    minimum_error_confidence: float = 0.65,
) -> list[HardSegment]:
    if not frames:
        return []
    difficult = [
        item.frame_index
        for item in frames
        if any(
            error.repairable and error.error_confidence >= minimum_error_confidence
            for error in item.errors
        )
    ]
    if not difficult:
        return []
    durations = np.diff(np.asarray(timestamps, dtype=np.float64))
    median_dt = float(np.median(durations[durations > 0.0])) if np.any(durations > 0.0) else 1.0 / 30.0
    padding = max(0, int(round(padding_seconds / max(median_dt, 1e-6))))
    groups: list[list[int]] = []
    for index in difficult:
        hard_lost = tracking_states[index].upper() in {"LOST", "TRACK_LOST"}
        if hard_lost and all(error.code == PoseErrorCode.OCCLUSION for error in frames[index].errors):
            continue
        if not groups or index - groups[-1][-1] > 2 or _has_cut(scene_cuts, groups[-1][-1] + 1, index):
            groups.append([index])
        else:
            groups[-1].append(index)
    candidates: list[HardSegment] = []
    for group in groups:
        start = group[0]
        end = group[-1]
        for _ in range(padding):
            if start > 0 and not scene_cuts[start]:
                start -= 1
            if end + 1 < len(frames) and not scene_cuts[end + 1]:
                end += 1
        selected = frames[start:end + 1]
        errors = [error for frame in selected for error in frame.errors]
        candidates.append(HardSegment(
            start, end,
            tuple(sorted({error.code for error in errors}, key=lambda item: item.value)),
            tuple(sorted({joint for error in errors for joint in error.joint_indexes})),
            float(np.mean([frame.quality_score for frame in selected])),
            max((error.severity for error in errors), default=0.0),
        ))
    maximum_frames = max(1, int(math.ceil(len(frames) * maximum_ratio))) if maximum_ratio > 0.0 else 0
    selected: list[HardSegment] = []
    used = 0
    for segment in sorted(candidates, key=lambda item: (item.quality_score, -item.severity, item.start_frame)):
        if used >= maximum_frames:
            break
        remaining = maximum_frames - used
        if segment.frame_count <= remaining:
            selected.append(segment)
            used += segment.frame_count
        elif remaining > 0:
            selected.append(HardSegment(
                segment.start_frame, segment.start_frame + remaining - 1,
                segment.error_codes, segment.affected_joint_indexes,
                segment.quality_score, segment.severity,
            ))
            used += remaining
    return sorted(selected, key=lambda item: item.start_frame)


def select_critical_segments(
    audit: PoseAuditResult, *, maximum_ratio: float,
) -> list[HardSegment]:
    if not audit.frames or not audit.hard_segments:
        return []
    budget = max(1, int(math.ceil(len(audit.frames) * maximum_ratio)))
    output: list[HardSegment] = []
    used = 0
    for item in sorted(audit.hard_segments, key=lambda segment: (segment.quality_score, -segment.severity)):
        if used >= budget:
            break
        count = min(item.frame_count, budget - used)
        output.append(HardSegment(
            item.start_frame, item.start_frame + count - 1, item.error_codes,
            item.affected_joint_indexes, item.quality_score, item.severity, True,
        ))
        used += count
    return sorted(output, key=lambda item: item.start_frame)


def fuse_pose_hypotheses(
    hypotheses: Sequence[PoseHypothesis],
    *,
    body_scale: float,
    previous_points: np.ndarray | None = None,
    following_points: np.ndarray | None = None,
    minimum_quality_gain: float = 0.01,
) -> ConsensusFusionResult:
    """Robust per-joint medoid consensus with Pass 1 preservation."""

    if not hypotheses:
        raise ValueError("at least one pose hypothesis is required")
    shape = np.asarray(hypotheses[0].points).shape
    if len(shape) != 2 or shape[1] != 2:
        raise ValueError("pose hypothesis points must have shape (joints, 2)")
    joint_count = shape[0]
    baseline = hypotheses[0]
    output_points = np.asarray(baseline.points, dtype=np.float32).copy()
    output_scores = np.asarray(baseline.scores, dtype=np.float32).copy()
    metadata: list[dict[str, object]] = []
    corrected: set[int] = set()
    disagreement: set[int] = set()
    radius = max(2.0, float(body_scale) * 0.115)
    for joint in range(joint_count):
        observations: list[tuple[PoseHypothesis, np.ndarray, float]] = []
        for item in hypotheses:
            points_value = np.asarray(item.points, dtype=np.float32)
            scores_value = np.asarray(item.scores, dtype=np.float32)
            if joint >= len(scores_value):
                continue
            point = points_value[joint]
            score = float(scores_value[joint])
            if score > 0.0 and math.isfinite(score) and np.isfinite(point).all():
                observations.append((item, point, score))
        if not observations:
            metadata.append(_joint_metadata(baseline, 0.0, 0, False))
            continue
        distances = np.asarray([
            [float(np.linalg.norm(first[1] - second[1])) for second in observations]
            for first in observations
        ], dtype=np.float64)
        weights = np.asarray([
            max(0.01, score) * float(np.clip(item.source_trust, 0.0, 1.0))
            for item, _, score in observations
        ], dtype=np.float64)
        support = np.sum((distances <= radius) * weights[None, :], axis=1)
        medoid_index = int(np.argmax(support))
        medoid_item, medoid_point, medoid_score = observations[medoid_index]
        inlier_mask = distances[medoid_index] <= radius
        inlier_count = int(np.count_nonzero(inlier_mask))
        if inlier_count < len(observations):
            disagreement.add(joint)
        inlier_weights = weights[inlier_mask]
        inlier_points = np.stack([value[1] for value, keep in zip(observations, inlier_mask) if keep])
        consensus_point = np.average(inlier_points, axis=0, weights=inlier_weights).astype(np.float32)
        agreement = 1.0 - min(1.0, float(np.average(distances[medoid_index][inlier_mask], weights=inlier_weights)) / radius)
        confidence = float(np.average([value[2] for value, keep in zip(observations, inlier_mask) if keep], weights=inlier_weights))
        temporal = _temporal_point_agreement(consensus_point, joint, previous_points, following_points, body_scale)
        consensus_score = float(np.clip(0.50 * agreement + 0.28 * confidence + 0.14 * temporal + 0.08 * medoid_item.source_trust, 0.0, 1.0))
        baseline_score = float(baseline.scores[joint]) if joint < len(baseline.scores) else 0.0
        baseline_temporal = _temporal_point_agreement(output_points[joint], joint, previous_points, following_points, body_scale)
        baseline_trust = float(np.clip(0.72 * baseline_score + 0.20 * baseline_temporal + 0.08 * baseline.source_trust, 0.0, 1.0))
        accept = bool(
            medoid_item.pass_index > baseline.pass_index
            and inlier_count >= min(2, len(observations))
            and consensus_score >= baseline_trust + minimum_quality_gain
        )
        if baseline_score <= 0.0 and consensus_score > 0.35:
            accept = True
        if accept:
            output_points[joint] = consensus_point
            output_scores[joint] = float(np.clip(confidence * agreement, 0.0, 1.0))
            corrected.add(joint)
            selected = medoid_item
        else:
            selected = baseline
        metadata.append(_joint_metadata(selected, consensus_score, inlier_count, accept))
    return ConsensusFusionResult(
        output_points, output_scores, tuple(metadata), frozenset(corrected), frozenset(disagreement),
    )


def compare_iteration_quality(
    quality_before: float,
    quality_after: float,
    *,
    iteration: int,
    config: IterativeRefinementConfig,
) -> IterationDecision:
    before = float(np.clip(quality_before, 0.0, 1.0))
    after = float(np.clip(quality_after, 0.0, 1.0))
    delta = after - before
    rolled_back = delta < 0.0
    converged = abs(delta) < config.convergence_epsilon
    accepted = delta >= config.minimum_quality_gain
    return IterationDecision(
        accepted, converged, rolled_back, before, after, delta,
        iteration if accepted else max(1, iteration - 1),
    )


def select_best_iteration(
    quality_scores: Sequence[float], *, config: IterativeRefinementConfig,
) -> tuple[int, list[IterationDecision]]:
    """Select the best state and stop on regression or convergence.

    The returned index is one-based (Pass 1 == 1). Later scores are not
    inspected after the bounded stopping criterion fires.
    """

    if not quality_scores:
        raise ValueError("quality_scores cannot be empty")
    best_index = 1
    best_quality = float(np.clip(quality_scores[0], 0.0, 1.0))
    decisions: list[IterationDecision] = []
    for zero_index, proposed in enumerate(quality_scores[1:], start=1):
        decision = compare_iteration_quality(
            best_quality, proposed, iteration=zero_index + 1, config=config,
        )
        decisions.append(decision)
        if decision.accepted:
            best_quality = float(np.clip(proposed, 0.0, 1.0))
            best_index = zero_index + 1
        if decision.rolled_back or decision.converged:
            break
    return best_index, decisions


def optimize_global_trajectories(
    frames: Sequence[TemporalFrame],
    body_scales: Sequence[float],
    motion_states: Sequence[str],
    tracking_states: Sequence[str],
    scene_cuts: Sequence[bool],
    *,
    config: IterativeRefinementConfig,
    body_joint_count: int = 17,
    allowed_frame_indexes: set[int] | frozenset[int] | None = None,
    timestamps: Sequence[float] | None = None,
) -> GlobalOptimizationResult:
    """Confidence/source-weighted, joint-chain-aware coordinate descent.

    It repairs isolated jerk against bidirectional, seconds-based context and
    couples shoulder-elbow-wrist / hip-knee-ankle topology. Sustained fast
    motion and high-confidence measured samples remain anchors. Every sweep is
    compared with best-state history and rolled back on objective regression.
    """

    count = len(frames)
    if not (count == len(body_scales) == len(motion_states) == len(tracking_states) == len(scene_cuts)):
        raise ValueError("global optimization inputs must have equal lengths")
    if timestamps is not None and len(timestamps) != count:
        raise ValueError("global optimization timestamps must match frame count")
    if not frames:
        return GlobalOptimizationResult([], [], {
            "version": "global-trajectory-optimization-v2", "iterations": 0,
            "quality_score_before": 0.0, "quality_score_after": 0.0,
            "correction_count": 0, "rollback_count": 0, "converged": True,
        })
    working = [_copy_temporal_frame(frame) for frame in frames]
    best = [_copy_temporal_frame(frame) for frame in frames]
    measurement_reference = [_copy_temporal_frame(frame) for frame in frames]
    reference_bones = _bone_references(
        [frame.analysis_points for frame in frames],
        [frame.analysis_scores for frame in frames],
        body_joint_count,
    )
    before_objective = _trajectory_objective(
        best, body_scales, motion_states, tracking_states, scene_cuts,
        body_joint_count, measurement_reference=measurement_reference,
    )
    best_objective = before_objective
    corrections = np.zeros((count, len(frames[0].analysis_scores)), dtype=np.int32)
    rollback_count = 0
    iteration_records: list[dict[str, object]] = []
    converged = False
    coupled_chain_corrections = 0
    for iteration in range(1, config.maximum_repair_iterations + 1):
        changed = 0
        candidate_chain_corrections = 0
        candidate = [_copy_temporal_frame(frame) for frame in working]
        candidate_corrections = corrections.copy()
        for index in range(1, count - 1):
            if allowed_frame_indexes is not None and index not in allowed_frame_indexes:
                continue
            if scene_cuts[index] or scene_cuts[index + 1]:
                continue
            if tracking_states[index].upper() in {"LOST", "TRACK_LOST", "REACQUIRING"}:
                continue
            for joint in range(min(body_joint_count, len(candidate[index].analysis_scores))):
                current = candidate[index]
                previous_index, following_index = _bidirectional_context_indexes(
                    index,
                    count,
                    timestamps,
                    config.critical_temporal_context_seconds,
                    scene_cuts,
                )
                previous = working[previous_index]
                following = working[following_index]
                if not (current.analysis_usable[joint] and previous.analysis_usable[joint] and following.analysis_usable[joint]):
                    continue
                source = current.sources[joint].value
                source_trust = SOURCE_TRUST.get(source, 0.25)
                score = float(current.analysis_scores[joint])
                motion = motion_states[index].upper()
                if motion in {"FAST_MOTION", "EXTREME_MOTION"} and source_trust >= 0.90 and score >= 0.50:
                    continue
                left_velocity = current.analysis_points[joint] - previous.analysis_points[joint]
                right_velocity = following.analysis_points[joint] - current.analysis_points[joint]
                if _sustained_motion(left_velocity, right_velocity, body_scales[index], motion):
                    continue
                expected = _time_weighted_consensus(
                    previous.analysis_points[joint],
                    current.analysis_points[joint],
                    following.analysis_points[joint],
                    previous_index,
                    index,
                    following_index,
                    timestamps,
                )
                residual = current.analysis_points[joint] - expected
                normalized = float(np.linalg.norm(residual) / max(body_scales[index], 1.0))
                if not math.isfinite(normalized) or normalized < 0.075:
                    continue
                huber = min(1.0, 0.16 / max(normalized, 1e-6))
                age = float(current.prediction_age_seconds[joint])
                age_penalty = min(1.0, max(0.0, age) / 0.55) if math.isfinite(age) else 1.0
                occluded = tracking_states[index].upper() in {"PARTIAL", "OCCLUDED"}
                evidence_trust = source_trust * score * (1.0 - 0.35 * age_penalty)
                repair_weight = min(
                    0.62,
                    (1.0 - 0.72 * evidence_trust)
                    * (0.56 if occluded else 0.48)
                    * huber,
                )
                if motion in {"FAST_MOTION", "EXTREME_MOTION"}:
                    repair_weight *= 0.55
                if source_trust >= 0.90:
                    repair_weight = min(repair_weight, 0.16)
                repaired = current.analysis_points[joint] * (1.0 - repair_weight) + expected * repair_weight
                _replace_temporal_joint(candidate[index], joint, repaired)
                candidate_corrections[index, joint] += 1
                changed += 1
            chain_changes = _project_coupled_chains(
                candidate[index],
                reference_bones,
                motion_states[index],
                body_joint_count,
            )
            for joint in chain_changes:
                candidate_corrections[index, joint] += 1
            changed += len(chain_changes)
            candidate_chain_corrections += len(chain_changes)
        objective = _trajectory_objective(
            candidate, body_scales, motion_states, tracking_states, scene_cuts,
            body_joint_count, measurement_reference=measurement_reference,
        )
        quality_before = 1.0 / (1.0 + best_objective)
        quality_after = 1.0 / (1.0 + objective)
        decision = compare_iteration_quality(
            quality_before, quality_after, iteration=iteration, config=config,
        )
        iteration_records.append({"iteration": iteration, "changed_joint_count": changed, **decision.to_dict()})
        if decision.accepted:
            best = candidate
            best_objective = objective
            working = candidate
            corrections = candidate_corrections
            coupled_chain_corrections += candidate_chain_corrections
        else:
            if decision.rolled_back:
                rollback_count += 1
            working = [_copy_temporal_frame(frame) for frame in best]
        if changed == 0 or decision.converged:
            converged = True
            break
    diagnostics = [
        {
            "corrected_joint_indexes": [int(value) for value in np.flatnonzero(corrections[index])],
            "correction_count": int(np.sum(corrections[index])),
            "repair_iterations_by_joint": {
                str(joint): int(corrections[index, joint])
                for joint in np.flatnonzero(corrections[index])
            },
        }
        for index in range(count)
    ]
    return GlobalOptimizationResult(best, diagnostics, {
        "version": "global-trajectory-optimization-v2",
        "robust_loss": "huber-bidirectional-chain-context",
        "objective_terms": [
            "measurement", "velocity", "acceleration", "jerk",
            "bone_length", "joint_topology",
        ],
        "dynamic_weights": [
            "source", "model_trust", "motion_state", "occlusion_state",
            "prediction_age",
        ],
        "temporal_context_seconds": config.critical_temporal_context_seconds,
        "bidirectional_consensus": True,
        "coupled_joint_chains": [list(chain) for chain in COUPLED_JOINT_CHAINS],
        "coupled_chain_correction_count": coupled_chain_corrections,
        "source_hierarchy_enforced": True,
        "iterations": len(iteration_records),
        "iteration_diagnostics": iteration_records,
        "quality_score_before": round(1.0 / (1.0 + before_objective), 6),
        "quality_score_after": round(1.0 / (1.0 + best_objective), 6),
        "correction_count": int(np.sum(corrections)),
        "repaired_frames_count": int(np.count_nonzero(np.any(corrections > 0, axis=1))),
        "rollback_count": rollback_count,
        "converged": converged,
        "localized": allowed_frame_indexes is not None,
        "allowed_frame_count": (
            len(allowed_frame_indexes) if allowed_frame_indexes is not None else count
        ),
    })


def _bone_references(
    points: Sequence[np.ndarray], scores: Sequence[np.ndarray], joint_count: int,
) -> dict[tuple[int, int], float]:
    output: dict[tuple[int, int], float] = {}
    for first, second in DEFAULT_BODY_BONES:
        if first >= joint_count or second >= joint_count:
            continue
        values = [
            float(np.linalg.norm(frame[second] - frame[first]))
            for frame, frame_scores in zip(points, scores)
            if frame_scores[first] > 0.35 and frame_scores[second] > 0.35
            and np.isfinite(frame[[first, second]]).all()
        ]
        if values:
            output[(first, second)] = float(np.median(values))
    return output


def _temporal_errors(
    index: int,
    points: Sequence[np.ndarray],
    scores: Sequence[np.ndarray],
    body_scales: Sequence[float],
    scene_cuts: Sequence[bool],
    motion_states: Sequence[str],
    joint_count: int,
) -> tuple[float, list[PoseError]]:
    if index == 0 or index + 1 >= len(points) or scene_cuts[index] or scene_cuts[index + 1]:
        return 1.0, []
    errors: list[PoseError] = []
    residuals: list[float] = []
    gate = 2.2 if motion_states[index].upper() in {"FAST_MOTION", "EXTREME_MOTION"} else 1.0
    for joint in range(joint_count):
        if min(float(scores[index - 1][joint]), float(scores[index][joint]), float(scores[index + 1][joint])) <= 0.0:
            continue
        expected = (points[index - 1][joint] + points[index + 1][joint]) * 0.5
        residual = float(np.linalg.norm(points[index][joint] - expected) / max(body_scales[index], 1.0))
        if not math.isfinite(residual):
            continue
        residuals.append(residual)
        if residual > 0.18 * gate:
            severity = min(1.0, residual / (0.40 * gate))
            errors.append(PoseError(index, PoseErrorCode.JOINT_JUMP, (joint,), severity))
            errors.append(PoseError(index, PoseErrorCode.TEMPORAL_DISCONTINUITY, (joint,), severity))
    median = float(np.median(residuals)) if residuals else 0.0
    return float(np.clip(1.0 - median / (0.22 * gate), 0.0, 1.0)), errors


def _anatomy_errors(
    index: int,
    points: np.ndarray,
    scores: np.ndarray,
    body_scale: float,
    references: Mapping[tuple[int, int], float],
) -> tuple[float, list[PoseError]]:
    errors: list[PoseError] = []
    relative_errors: list[float] = []
    for pair, reference in references.items():
        first, second = pair
        if first >= len(scores) or second >= len(scores) or min(float(scores[first]), float(scores[second])) <= 0.0:
            continue
        length = float(np.linalg.norm(points[second] - points[first]))
        if not math.isfinite(length) or reference <= 0.0:
            continue
        relative = abs(length - reference) / reference
        relative_errors.append(relative)
        if relative > 0.30:
            errors.append(PoseError(index, PoseErrorCode.BONE_LENGTH_ERROR, pair, min(1.0, relative)))
    median = float(np.median(relative_errors)) if relative_errors else (0.0 if body_scale > 0.0 else 1.0)
    return float(np.clip(1.0 - median / 0.35, 0.0, 1.0)), errors


def _side_identity_errors(
    index: int,
    points: Sequence[np.ndarray],
    scores: Sequence[np.ndarray],
    body_scales: Sequence[float],
    scene_cuts: Sequence[bool],
    motion_states: Sequence[str],
) -> list[PoseError]:
    if index == 0 or index + 1 >= len(points) or scene_cuts[index] or scene_cuts[index + 1]:
        return []
    output: list[PoseError] = []
    gate = 1.8 if motion_states[index].upper() in {"FAST_MOTION", "EXTREME_MOTION"} else 1.0
    for left, right in ((5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16)):
        if max(left, right) >= len(scores[index]) or min(
            float(scores[index - 1][left]), float(scores[index - 1][right]),
            float(scores[index][left]), float(scores[index][right]),
            float(scores[index + 1][left]), float(scores[index + 1][right]),
        ) <= 0.0:
            continue
        expected_left = (points[index - 1][left] + points[index + 1][left]) * 0.5
        expected_right = (points[index - 1][right] + points[index + 1][right]) * 0.5
        same = float(np.linalg.norm(points[index][left] - expected_left) + np.linalg.norm(points[index][right] - expected_right))
        swapped = float(np.linalg.norm(points[index][right] - expected_left) + np.linalg.norm(points[index][left] - expected_right))
        margin = max(body_scales[index], 1.0) * 0.10 * gate
        if swapped + margin < same:
            severity = min(1.0, (same - swapped) / max(body_scales[index], 1.0))
            output.append(PoseError(index, PoseErrorCode.LEFT_RIGHT_AMBIGUITY, (left, right), severity))
    return output


def _angle(points: np.ndarray, scores: np.ndarray, first: int, center: int, third: int) -> float | None:
    if max(first, center, third) >= len(scores) or min(float(scores[first]), float(scores[center]), float(scores[third])) <= 0.0:
        return None
    first_vector = points[first] - points[center]
    second_vector = points[third] - points[center]
    norms = float(np.linalg.norm(first_vector) * np.linalg.norm(second_vector))
    if norms <= 1e-6 or not np.isfinite(first_vector).all() or not np.isfinite(second_vector).all():
        return None
    cosine = float(np.clip(np.dot(first_vector, second_vector) / norms, -1.0, 1.0))
    return math.degrees(math.acos(cosine))


def _deduplicate_errors(errors: Sequence[PoseError]) -> list[PoseError]:
    output: dict[tuple[PoseErrorCode, tuple[int, ...]], PoseError] = {}
    for error in errors:
        key = (error.code, error.joint_indexes)
        previous = output.get(key)
        if previous is None or error.severity > previous.severity:
            output[key] = error
    return sorted(output.values(), key=lambda item: (item.code.value, item.joint_indexes))


def _has_cut(scene_cuts: Sequence[bool], start: int, end: int) -> bool:
    return any(bool(scene_cuts[index]) for index in range(max(0, start), min(len(scene_cuts), end + 1)))


def _temporal_point_agreement(
    point: np.ndarray, joint: int, previous: np.ndarray | None,
    following: np.ndarray | None, body_scale: float,
) -> float:
    references = []
    for value in (previous, following):
        if value is not None and joint < len(value) and np.isfinite(value[joint]).all():
            references.append(value[joint])
    if not references:
        return 0.75
    expected = np.mean(np.stack(references), axis=0)
    residual = float(np.linalg.norm(point - expected) / max(body_scale, 1.0))
    return float(np.clip(1.0 - residual / 0.30, 0.0, 1.0))


def _joint_metadata(
    selected: PoseHypothesis, consensus: float, support: int, corrected: bool,
) -> dict[str, object]:
    return {
        "selected_pass": selected.pass_index,
        "selected_source": selected.source,
        "consensus_score": round(consensus, 6),
        "correction_count": 1 if corrected else 0,
        "consensus_support": support,
    }


def _copy_temporal_frame(frame: TemporalFrame) -> TemporalFrame:
    return TemporalFrame(
        frame.analysis_points.copy(), frame.analysis_scores.copy(),
        frame.render_points.copy(), frame.render_scores.copy(), frame.sources,
        frame.analysis_usable.copy(), frame.prediction_age_seconds.copy(),
        frame.flow_errors.copy(),
    )


def _replace_temporal_joint(frame: TemporalFrame, joint: int, point: np.ndarray) -> None:
    # TemporalFrame is frozen, but its NumPy buffers are intentionally copied
    # per candidate state and remain mutable within this numerical routine.
    frame.analysis_points[joint] = point
    if frame.render_scores[joint] > 0.0:
        frame.render_points[joint] = point


def _sustained_motion(
    previous_velocity: np.ndarray, following_velocity: np.ndarray,
    body_scale: float, motion_state: str,
) -> bool:
    first = float(np.linalg.norm(previous_velocity))
    second = float(np.linalg.norm(following_velocity))
    if min(first, second) <= 1e-6:
        return False
    cosine = float(np.dot(previous_velocity, following_velocity) / (first * second))
    speed = max(first, second) / max(body_scale, 1.0)
    threshold = 0.06 if motion_state.upper() in {"FAST_MOTION", "EXTREME_MOTION"} else 0.12
    return cosine > 0.45 and speed > threshold


def _bidirectional_context_indexes(
    index: int,
    count: int,
    timestamps: Sequence[float] | None,
    context_seconds: float,
    scene_cuts: Sequence[bool],
) -> tuple[int, int]:
    """Choose bounded past/future evidence using seconds, never crossing cuts."""

    previous = index - 1
    following = index + 1
    if timestamps is None:
        maximum_steps = max(1, int(round(context_seconds * 30.0)))
        target_previous = max(0, index - maximum_steps)
        target_following = min(count - 1, index + maximum_steps)
    else:
        target_previous = previous
        target_following = following
        for candidate in range(index - 1, -1, -1):
            if scene_cuts[candidate + 1]:
                break
            if float(timestamps[index]) - float(timestamps[candidate]) <= context_seconds + 1e-9:
                target_previous = candidate
            else:
                break
        for candidate in range(index + 1, count):
            if scene_cuts[candidate]:
                break
            if float(timestamps[candidate]) - float(timestamps[index]) <= context_seconds + 1e-9:
                target_following = candidate
            else:
                break
    if not _has_cut(scene_cuts, target_previous + 1, index):
        previous = target_previous
    if not _has_cut(scene_cuts, index + 1, target_following):
        following = target_following
    return previous, following


def _time_weighted_consensus(
    previous: np.ndarray,
    current: np.ndarray,
    following: np.ndarray,
    previous_index: int,
    current_index: int,
    following_index: int,
    timestamps: Sequence[float] | None,
) -> np.ndarray:
    """Interpolate the forward/backward estimates at the current instant."""

    if timestamps is None:
        denominator = following_index - previous_index
        ratio = (
            (current_index - previous_index) / denominator
            if denominator > 0 else 0.5
        )
    else:
        before = float(timestamps[previous_index])
        after = float(timestamps[following_index])
        ratio = (
            (float(timestamps[current_index]) - before) / (after - before)
            if math.isfinite(before) and math.isfinite(after) and after > before
            else 0.5
        )
    ratio = float(np.clip(ratio, 0.0, 1.0))
    temporal = previous * (1.0 - ratio) + following * ratio
    # Current contributes only a small robust anchor. The repair weight applied
    # by the caller still decides how far the candidate may move.
    return (temporal * 0.88 + current * 0.12).astype(np.float32)


def _project_coupled_chains(
    frame: TemporalFrame,
    bone_references: Mapping[tuple[int, int], float],
    motion_state: str,
    body_joint_count: int,
) -> set[int]:
    """Apply a bounded topology correction to complete limb chains."""

    changed: set[int] = set()
    for first, middle, last in COUPLED_JOINT_CHAINS:
        if last >= body_joint_count or not all(
            frame.analysis_usable[joint] for joint in (first, middle, last)
        ):
            continue
        first_length = bone_references.get((first, middle))
        second_length = bone_references.get((middle, last))
        if first_length is None or second_length is None:
            continue
        first_vector = frame.analysis_points[middle] - frame.analysis_points[first]
        second_vector = frame.analysis_points[last] - frame.analysis_points[middle]
        first_actual = float(np.linalg.norm(first_vector))
        second_actual = float(np.linalg.norm(second_vector))
        if min(first_actual, second_actual, first_length, second_length) <= 1e-6:
            continue
        first_error = abs(first_actual - first_length) / first_length
        second_error = abs(second_actual - second_length) / second_length
        if max(first_error, second_error) < 0.14:
            continue
        source_trust = min(
            SOURCE_TRUST.get(frame.sources[joint].value, 0.25)
            * float(frame.analysis_scores[joint])
            for joint in (middle, last)
        )
        if (
            motion_state.upper() in {"FAST_MOTION", "EXTREME_MOTION"}
            and source_trust >= 0.55
        ):
            continue
        weight = min(0.30, 0.10 + 0.25 * (1.0 - source_trust))
        middle_target = (
            frame.analysis_points[first]
            + first_vector / first_actual * first_length
        )
        middle_value = (
            frame.analysis_points[middle] * (1.0 - weight)
            + middle_target * weight
        )
        last_target = middle_value + second_vector / second_actual * second_length
        last_value = (
            frame.analysis_points[last] * (1.0 - weight)
            + last_target * weight
        )
        _replace_temporal_joint(frame, middle, middle_value.astype(np.float32))
        _replace_temporal_joint(frame, last, last_value.astype(np.float32))
        changed.update((middle, last))
    return changed


def _chain_angle(
    points: np.ndarray, first: int, middle: int, last: int,
) -> float | None:
    first_vector = points[first] - points[middle]
    second_vector = points[last] - points[middle]
    denominator = float(np.linalg.norm(first_vector) * np.linalg.norm(second_vector))
    if denominator <= 1e-8 or not np.isfinite(first_vector).all() or not np.isfinite(second_vector).all():
        return None
    cosine = float(np.clip(np.dot(first_vector, second_vector) / denominator, -1.0, 1.0))
    return math.degrees(math.acos(cosine))


def _trajectory_objective(
    frames: Sequence[TemporalFrame],
    body_scales: Sequence[float],
    motion_states: Sequence[str],
    tracking_states: Sequence[str],
    scene_cuts: Sequence[bool],
    body_joint_count: int,
    *,
    measurement_reference: Sequence[TemporalFrame] | None = None,
) -> float:
    residuals: list[float] = []
    bone_references: dict[tuple[int, int], float] = {}
    for first, second in DEFAULT_BODY_BONES:
        if max(first, second) >= body_joint_count:
            continue
        lengths = [
            float(np.linalg.norm(frame.analysis_points[second] - frame.analysis_points[first]))
            for frame in frames
            if frame.analysis_usable[first] and frame.analysis_usable[second]
        ]
        finite = [value for value in lengths if math.isfinite(value) and value > 1e-6]
        if finite:
            bone_references[(first, second)] = float(np.median(finite))
    for index in range(1, len(frames) - 1):
        if scene_cuts[index] or scene_cuts[index + 1] or tracking_states[index].upper() in {"LOST", "TRACK_LOST"}:
            continue
        for joint in range(min(body_joint_count, len(frames[index].analysis_scores))):
            if not all(frames[value].analysis_usable[joint] for value in (index - 1, index, index + 1)):
                continue
            left = frames[index].analysis_points[joint] - frames[index - 1].analysis_points[joint]
            right = frames[index + 1].analysis_points[joint] - frames[index].analysis_points[joint]
            if _sustained_motion(left, right, body_scales[index], motion_states[index]):
                continue
            jerk = float(np.linalg.norm(right - left) / max(body_scales[index], 1.0))
            delta = 0.12
            huber = 0.5 * jerk * jerk if jerk <= delta else delta * (jerk - 0.5 * delta)
            trust = SOURCE_TRUST.get(frames[index].sources[joint].value, 0.25)
            motion_factor = 0.42 if motion_states[index].upper() in {"FAST_MOTION", "EXTREME_MOTION"} else 1.0
            residuals.append(huber * (1.15 - 0.35 * trust) * motion_factor)
            velocity_scale = max(body_scales[index], 1.0)
            residuals.append(0.20 * motion_factor * abs(float(np.linalg.norm(left)) - float(np.linalg.norm(right))) / velocity_scale)
            if measurement_reference is not None and frames[index].analysis_usable[joint]:
                measurement_delta = float(np.linalg.norm(
                    frames[index].analysis_points[joint]
                    - measurement_reference[index].analysis_points[joint]
                )) / velocity_scale
                age = float(frames[index].prediction_age_seconds[joint])
                age_factor = 1.0 - min(0.75, max(0.0, age) / 0.55) if math.isfinite(age) else 0.25
                residuals.append(0.18 * trust * age_factor * measurement_delta)
            if 1 < index < len(frames) - 2 and not scene_cuts[index - 1] and not scene_cuts[index + 2]:
                previous_velocity = frames[index - 1].analysis_points[joint] - frames[index - 2].analysis_points[joint]
                following_velocity = frames[index + 2].analysis_points[joint] - frames[index + 1].analysis_points[joint]
                jerk_residual = float(np.linalg.norm(
                    (right - left) - (following_velocity - previous_velocity) * 0.5
                )) / velocity_scale
                residuals.append(0.12 * motion_factor * min(jerk_residual, 1.0))
        for (first, second), reference in bone_references.items():
            if not (frames[index].analysis_usable[first] and frames[index].analysis_usable[second]):
                continue
            length = float(np.linalg.norm(
                frames[index].analysis_points[second] - frames[index].analysis_points[first]
            ))
            relative = abs(length - reference) / reference
            delta = 0.20
            huber = 0.5 * relative * relative if relative <= delta else delta * (relative - 0.5 * delta)
            residuals.append(0.8 * huber)
        for first, middle, last in COUPLED_JOINT_CHAINS:
            if last >= body_joint_count or not all(
                frames[index].analysis_usable[joint]
                for joint in (first, middle, last)
            ):
                continue
            current_angle = _chain_angle(frames[index].analysis_points, first, middle, last)
            previous_angle = _chain_angle(frames[index - 1].analysis_points, first, middle, last)
            following_angle = _chain_angle(frames[index + 1].analysis_points, first, middle, last)
            if None not in (current_angle, previous_angle, following_angle):
                topology_residual = abs(
                    float(current_angle) - (float(previous_angle) + float(following_angle)) * 0.5
                ) / 180.0
                residuals.append(0.35 * min(topology_residual, 1.0))
    return float(np.mean(residuals)) if residuals else 0.0


__all__ = [
    "ConsensusFusionResult", "FrameAudit", "GlobalOptimizationResult",
    "HardSegment", "IterationDecision", "PoseAuditResult", "PoseError",
    "Repairability",
    "PoseErrorCode", "PoseHypothesis", "audit_pose_sequence",
    "compare_iteration_quality", "detect_angle_glitches",
    "detect_grip_flicker", "fuse_pose_hypotheses", "group_hard_segments",
    "normalize_joint_age_vector", "normalize_joint_mask",
    "optimize_global_trajectories", "PoseAuditInputError",
    "select_critical_segments",
    "select_best_iteration",
]
